#ifndef YUGIOH_GAME_AI_CONSTANTS_H
#define YUGIOH_GAME_AI_CONSTANTS_H

#define AI_ACTIVE_CARD_RECORD_SIZE 0x0C
#define AI_ACTIVE_CARD_SIDE_BYTE_STRIDE 0x294

#define AI_SCRIPT_CARD_SET_COUNT 32
#define AI_SCRIPT_COMBO_CARD_COUNT 6
#define AI_SCRIPT_PERCENT_SCALE 100
#define AI_SCRIPT_MEMORY_COUNT 20
#define AI_SCRIPT_RETURN_STACK_COUNT 8
#define AI_SCRIPT_TYPE_SET_COUNT 25
#define AI_SCRIPT_CARD_SET_EMPTY 0
#define AI_SCRIPT_TYPE_SET_EMPTY 0
#define AI_SCRIPT_TYPE_SET_ENCODING_BIAS 1
#define AI_SCRIPT_CARD_SET_BYTE_OFFSET 0x3E
#define AI_SCRIPT_CARD_SET_ENTRY_SIZE 2
#define AI_SCRIPT_CARD_SET_HALFWORD_OFFSET \
    (AI_SCRIPT_CARD_SET_BYTE_OFFSET / AI_SCRIPT_CARD_SET_ENTRY_SIZE)
#define AI_SCRIPT_TYPE_SET_BYTE_OFFSET 0x7E

#define AI_SCRIPT_COMBO_BYTE_OFFSET 0x38
#define AI_SCRIPT_FUSION_COUNT_BYTE_OFFSET 0x9C
#define AI_SCRIPT_FUSION_LIMIT_BYTE_OFFSET 0x9D
#define AI_SCRIPT_FUSION_SET_BYTE_OFFSET 0x9E
#define AI_SCRIPT_FUSION_BEST_STAT_BYTE_OFFSET 0xA0
#define AI_SCRIPT_FUSION_DEPTH_BYTE_OFFSET 0xA2
#define AI_SCRIPT_FUSION_BEST_DEPTH_BYTE_OFFSET 0xA3
#define AI_SCRIPT_FUSION_PATH_BYTE_OFFSET 0xA4
#define AI_SCRIPT_FUSION_USED_BYTE_OFFSET 0xAA

#endif
