#include "../types.h"
#include "ai_script_commands.h"
#include "ai_script_end.h"

/* Initialized data at 0x800916E0: the opcode dispatch table AiScript_Run
   indexes. Opcode 0 is unused and its slot is null. */
AiScriptHandler gAiScript_apfnCommand[68] = {
    (AiScriptHandler)0,
    AiScript_Jump,
    AiScript_JumpGreaterEqual,
    AiScript_JumpGreater,
    AiScript_JumpEqual,
    AiScript_JumpNotEqual,
    AiScript_JumpBetween,
    AiScript_JumpRandom,
    AiScript_Call,
    AiScript_Return,
    AiScript_SetRandom,
    AiScript_Subtract,
    AiScript_PlayFieldCard,
    AiScript_EndHand,
    AiScript_EndField,
    AiScript_CalcCardPower,
    AiScript_TestHighStat,
    AiScript_LoadCardType,
    AiScript_LoadCardID,
    AiScript_SetFaceDown,
    AiScript_LoadLifePoint,
    AiScript_LoadOpponentID,
    AiScript_LoadTerrain,
    AiScript_LoadDeckSize,
    func_80071510,
    AiScript_TestPinned,
    AiScript_StartCombo,
    AiScript_LoadBestDifference,
    AiScript_LoadBestAttacker,
    AiScript_LoadBestTarget,
    AiScript_FindStrongest,
    AiScript_FindWeakest,
    AiScript_FindKiller,
    AiScript_FindDefenseStopper,
    AiScript_CountCards,
    AiScript_FindFirstCard,
    AiScript_FindCard,
    AiScript_MatchType,
    AiScript_FindEquipTarget,
    AiScript_CheckRitual,
    AiScript_FindFirstMonster,
    AiScript_FindFirstType,
    AiScript_FindBestCombo,
    AiScript_EvaluateFusion,
    AiScript_SkipHand,
    AiScript_SkipField,
    AiScript_PlayFaceUp,
    AiScript_SetPosition,
    AiScript_FindBestAttack,
    AiScript_PushComboCard,
    AiScript_PushComboEmpty,
    AiScript_HandNop,
    AiScript_FieldNop,
    AiScript_AddCard,
    AiScript_ClearCards,
    AiScript_AddType,
    AiScript_ClearTypes,
    func_80073448,
    func_80073458,
    func_80073464,
    func_80073474,
    AiScript_MoveCard,
    AiScript_LoadOpponentData,
    AiScript_Store,
    AiScript_SetRegister,
    AiScript_Add,
    func_8007368C,
    AiScript_Print,
};
