#ifndef MEMORIES_DECOMP_CAMPAIGN_FLAGS_H
#define MEMORIES_DECOMP_CAMPAIGN_FLAGS_H

#define CAMPAIGN_FLAG_ID_MASK 0x7FF

/* Tests require a clear bit; updates clear it when this modifier is set. */
#define CAMPAIGN_FLAG_CLEAR_MODIFIER 0x8000
#define CAMPAIGN_FLAG_COMMAND_WRITE 0x4000
#define CAMPAIGN_FLAG_COMMAND_WORD_MASK 0xFFFF
#define CAMPAIGN_FLAG_COMMAND_PAYLOAD_MASK \
    (CAMPAIGN_FLAG_COMMAND_WORD_MASK ^ CAMPAIGN_FLAG_COMMAND_WRITE)

#endif
