#ifndef MEMORIES_DECOMP_CARD_CONSTANTS_H
#define MEMORIES_DECOMP_CARD_CONSTANTS_H

#define CARD_COUNT 722
#define DECK_SIZE 40
#define DUEL_DROP_WEIGHT_TOTAL 2048

#define CARD_TYPE_MAGIC 20
#define CARD_TYPE_TRAP 21
#define CARD_TYPE_RITUAL 22
#define CARD_TYPE_EQUIP 23

#endif
