#ifndef MEMORIES_DECOMP_CARD_CONSTANTS_H
#define MEMORIES_DECOMP_CARD_CONSTANTS_H

#define CARD_COUNT 722
#define HAND_SIZE 5
#define DECK_SIZE 40
#define COMBINED_DECK_SIZE (DECK_SIZE * 2)
#define DECK_CARD_COPY_LIMIT 3
/* Retail starter generation ignores the final two weight entries. */
#define STARTER_DECK_WEIGHT_SCAN_COUNT (CARD_COUNT - 2)
#define DUEL_DECK_SHUFFLE_SWAP_COUNT (DECK_SIZE * 4)
#define DUEL_RECENT_CARD_DROP_COUNT 16
#define DUEL_DROP_WEIGHT_TOTAL 2048
#define DUEL_DROP_TABLE_PADDING_SIZE 16
#define DUEL_LIFE_POINT_EFFECT_COUNT 5
#define DUEL_LIFE_POINT_RECOVERY_SCALE 100
#define DUEL_DIRECT_DAMAGE_SCALE 10
#define DUEL_ATTACK_TRAP_FIRST_CARD_ID 681
#define DUEL_ATTACK_TRAP_COUNT 6
#define DUEL_ATTACK_TRAP_THRESHOLD_SCALE 100
#define DUEL_FAKE_TRAP_CARD_ID 690
#define CARD_STAT_VALUE_MASK 0x1FF
#define CARD_STAT_DEFENSE_SHIFT 9
#define CARD_STAT_GUARDIAN_STAR_2_SHIFT 18
#define CARD_STAT_GUARDIAN_STAR_1_SHIFT 22
#define CARD_STAT_GUARDIAN_STAR_MASK 0xF
#define CARD_STAT_TYPE_SHIFT 26
#define CARD_STAT_TYPE_MASK 0x1F
#define CARD_STAT_SCALE 10
#define CARD_STAT_MAX 9999
#define FUSION_TABLE_ENTRY_SIZE 5
#define FUSION_TABLE_PAIRS_PER_ENTRY 2
#define FUSION_TABLE_EXTENDED_COUNT_BASE 0x1FF
#define FUSION_TABLE_CARD_ID_HIGH_MASK 0x300
#define FUSION_TABLE_FIRST_PARTNER_SHIFT 8
#define FUSION_TABLE_FIRST_RESULT_SHIFT 6
#define FUSION_TABLE_SECOND_PARTNER_SHIFT 4
#define FUSION_TABLE_SECOND_RESULT_SHIFT 2

#define EXODIA_FIRST_CARD_ID 0x11
#define EXODIA_PIECE_COUNT 5
#define EXODIA_CARD_ID_END (EXODIA_FIRST_CARD_ID + EXODIA_PIECE_COUNT)

/* Numeric encoding is executable-backed; category labels follow Data Crystal. */
#define CARD_TYPE_MAGIC 20
#define CARD_TYPE_TRAP 21
#define CARD_TYPE_RITUAL 22
#define CARD_TYPE_EQUIP 23

#endif
