#ifndef MEMORIES_DECOMP_CARD_CONSTANTS_H
#define MEMORIES_DECOMP_CARD_CONSTANTS_H

#define CARD_COUNT 722
#define HAND_SIZE 5
#define DECK_SIZE 40
#define DUEL_RECENT_CARD_DROP_COUNT 16
#define DUEL_DROP_WEIGHT_TOTAL 2048
#define DUEL_DROP_TABLE_PADDING_SIZE 16
#define CARD_STAT_VALUE_MASK 0x1FF
#define CARD_STAT_DEFENSE_SHIFT 9
#define CARD_STAT_GUARDIAN_STAR_2_SHIFT 18
#define CARD_STAT_GUARDIAN_STAR_1_SHIFT 22
#define CARD_STAT_GUARDIAN_STAR_MASK 0xF
#define CARD_STAT_TYPE_SHIFT 26
#define CARD_STAT_TYPE_MASK 0x1F
#define CARD_STAT_SCALE 10
#define FUSION_TABLE_ENTRY_SIZE 5
#define FUSION_TABLE_PAIRS_PER_ENTRY 2

#define EXODIA_FIRST_CARD_ID 0x11
#define EXODIA_PIECE_COUNT 5
#define EXODIA_CARD_ID_END (EXODIA_FIRST_CARD_ID + EXODIA_PIECE_COUNT)

/* Numeric encoding is executable-backed; category labels follow Data Crystal. */
#define CARD_TYPE_MAGIC 20
#define CARD_TYPE_TRAP 21
#define CARD_TYPE_RITUAL 22
#define CARD_TYPE_EQUIP 23

#endif
