#ifndef MEMORIES_DECOMP_COLOR_CONSTANTS_H
#define MEMORIES_DECOMP_COLOR_CONSTANTS_H

#define COLOR_FIXED_SHIFT 12
#define COLOR_FIXED_ONE (1 << COLOR_FIXED_SHIFT)
#define COLOR_FIXED_HALF (COLOR_FIXED_ONE / 2)
#define COLOR_HUE_SECTOR_COUNT 6
#define COLOR_HUE_FULL_TURN (COLOR_HUE_SECTOR_COUNT * COLOR_FIXED_ONE)

#endif
