#ifndef MEMORIES_DECOMP_COLOR_CONSTANTS_H
#define MEMORIES_DECOMP_COLOR_CONSTANTS_H

#define COLOR_FIXED_SHIFT 12
#define COLOR_FIXED_ONE (1 << COLOR_FIXED_SHIFT)
#define COLOR_FIXED_HALF (COLOR_FIXED_ONE / 2)
#define COLOR_HUE_SECTOR_COUNT 6
#define COLOR_HUE_FULL_TURN (COLOR_HUE_SECTOR_COUNT * COLOR_FIXED_ONE)

#define COLOR_TINT_HUE_MASK 0x7
#define COLOR_TINT_GRAYSCALE 6
#define COLOR_TINT_KEEP_HUE 7
#define COLOR_TINT_INVERT 0x8

#define COLOR_BGR555_CHANNEL_BITS 5
#define COLOR_BGR555_CHANNEL_MASK ((1 << COLOR_BGR555_CHANNEL_BITS) - 1)
#define COLOR_BGR555_GREEN_SHIFT COLOR_BGR555_CHANNEL_BITS
#define COLOR_BGR555_BLUE_SHIFT (2 * COLOR_BGR555_CHANNEL_BITS)
#define COLOR_BGR555_STP_MASK (1 << (3 * COLOR_BGR555_CHANNEL_BITS))

/* Neutral greys stored in the low 24 bits of SDK sprite/object colour words.
 * Equal channels make the byte order irrelevant. */
#define COLOR_RGB24_NEUTRAL_GREY 0x808080
#define COLOR_RGB24_DIM_GREY 0x404040

#endif
