#ifndef MEMORIES_DECOMP_DEBUG_EFFECT_STATE_H
#define MEMORIES_DECOMP_DEBUG_EFFECT_STATE_H

#include "../types.h"

#ifndef DEBUG_EFFECT_COORDINATE_OFFSET
#define DEBUG_EFFECT_COORDINATE_OFFSET 2
#endif
#ifndef DEBUG_EFFECT_PAGE_OFFSET
#define DEBUG_EFFECT_PAGE_OFFSET 4
#endif
#ifndef DEBUG_EFFECT_STATE_SIZE
#define DEBUG_EFFECT_STATE_SIZE 6
#endif

extern u8 gDebugEffect_abPreviewState[DEBUG_EFFECT_STATE_SIZE];

#endif
