#ifndef DISPLAY_OBJECT_LAYOUT_H
#define DISPLAY_OBJECT_LAYOUT_H

#define DISPLAY_OBJECT_RECORD_SIZE 0x70
#define DISPLAY_OBJECT_POOL_CAPACITY 96
#define DISPLAY_OBJECT_RESERVED_CAPACITY 16
#define DISPLAY_OBJECT_LIST_COUNT 7

#define DISPLAY_OBJECT_FLAG_ALLOCATED 0x80
#define DISPLAY_OBJECT_RENDERABLE_MASK 0xC0

#endif
