#ifndef MEMORIES_DECOMP_DUEL_MONSTER_REMOVAL_RULES_H
#define MEMORIES_DECOMP_DUEL_MONSTER_REMOVAL_RULES_H

#include "../types.h"

#define DUEL_MONSTER_REMOVAL_CARD_ID_BASE 600
#define DUEL_MONSTER_REMOVAL_RULE_SIZE 2
#define DUEL_MONSTER_REMOVAL_SELECTOR_OFFSET 1
#define DUEL_MONSTER_REMOVAL_RULE_COUNT 7

extern u8 gDuel_abMonsterRemovalRules[];

#endif
