#ifndef MEMORIES_DECOMP_DUEL_DISPLAY_H
#define MEMORIES_DECOMP_DUEL_DISPLAY_H

#define DUEL_DISPLAY_COLOR_NORMAL 0x808080
#define DUEL_DISPLAY_COLOR_DIMMED 0x404040

#define DUEL_CARD_READBACK_WIDTH_WORDS 0x8C
#define DUEL_CARD_READBACK_HEIGHT 0xC4
#define DUEL_CARD_READBACK_WORD_COUNT \
    (DUEL_CARD_READBACK_WIDTH_WORDS * DUEL_CARD_READBACK_HEIGHT)

#endif
