#include "../types.h"
#include "../unmatched.h"
#include "duel_effect_noop_handlers.h"
#include "duel_effect_tables.h"
#include "duel_ritual_effect.h"
#include "duel_action_lock.h"
#include "duel_card_effects.h"
#include "duel_field_effect_steps.h"
#include "duel_magic_effect_dispatch.h"
#include "duel_swords_effect.h"
#include "func_80028310.h"
#include "func_800283F4.h"

/* Initialized data at 0x80090A5C: two handlers per effect group, in group
   order. */
DuelEffectHandler gDuelEffect_apfnGroupHandler
    [DUEL_EFFECT_GROUP_COUNT * DUEL_CARD_EFFECT_HANDLERS_PER_GROUP] = {
    func_80024E4C, func_80024E4C,
    func_80024E4C, DuelEffect_ApplyTerrain,
    func_80024E4C, DuelEffect_ApplyLifePointRecovery,
    func_80024E4C, DuelEffect_ApplyDirectDamage,
    func_80024E4C, DuelEffect_ApplyBoardDestruction,
    func_80024E4C, DuelEffect_ApplyMonsterRemoval,
    func_80024E4C, DuelEffect_ApplyStopDefense,
    func_80024E4C, DuelEffect_ApplyRaigeki,
    func_80024E4C, DuelEffect_ApplyDarkPiercingLight,
    func_80024E4C, DuelEffect_ApplyStatPenalty,
    DuelEffect_StartSwords, DuelEffect_ApplySwords,
    func_80024E4C, DuelEffect_ApplyCursebreaker,
    DuelEffect_StartRitual, DuelEffect_ApplyRitual,
    func_80024E4C, DuelEffect_ApplyHarpiesFeatherDuster,
    func_80024E4C, func_80024E4C,
};

/* The group each card effect id dispatches to. */
u8 gDuelEffect_abGroupByEffectId[DUEL_EFFECT_ID_COUNT] = {
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_STOP_DEFENSE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_BOARD_DESTRUCTION, DUEL_EFFECT_GROUP_TERRAIN,
    DUEL_EFFECT_GROUP_TERRAIN, DUEL_EFFECT_GROUP_TERRAIN,
    DUEL_EFFECT_GROUP_TERRAIN, DUEL_EFFECT_GROUP_TERRAIN,
    DUEL_EFFECT_GROUP_TERRAIN, DUEL_EFFECT_GROUP_BOARD_DESTRUCTION,
    DUEL_EFFECT_GROUP_RAIGEKI, DUEL_EFFECT_GROUP_LIFE_POINT_RECOVERY,
    DUEL_EFFECT_GROUP_LIFE_POINT_RECOVERY,
    DUEL_EFFECT_GROUP_LIFE_POINT_RECOVERY,
    DUEL_EFFECT_GROUP_LIFE_POINT_RECOVERY,
    DUEL_EFFECT_GROUP_LIFE_POINT_RECOVERY,
    DUEL_EFFECT_GROUP_DIRECT_DAMAGE, DUEL_EFFECT_GROUP_DIRECT_DAMAGE,
    DUEL_EFFECT_GROUP_DIRECT_DAMAGE, DUEL_EFFECT_GROUP_DIRECT_DAMAGE,
    DUEL_EFFECT_GROUP_DIRECT_DAMAGE, DUEL_EFFECT_GROUP_SWORDS,
    DUEL_EFFECT_GROUP_STAT_PENALTY,
    DUEL_EFFECT_GROUP_DARK_PIERCING_LIGHT,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_MONSTER_REMOVAL, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_CURSEBREAKER, DUEL_EFFECT_GROUP_MONSTER_REMOVAL,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_MONSTER_REMOVAL,
    DUEL_EFFECT_GROUP_MONSTER_REMOVAL,
    DUEL_EFFECT_GROUP_MONSTER_REMOVAL,
    DUEL_EFFECT_GROUP_MONSTER_REMOVAL,
    DUEL_EFFECT_GROUP_MONSTER_REMOVAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_STAT_PENALTY, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_HARPIES_FEATHER_DUSTER,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_RITUAL,
    DUEL_EFFECT_GROUP_RITUAL, DUEL_EFFECT_GROUP_NONE,
    DUEL_EFFECT_GROUP_NONE, DUEL_EFFECT_GROUP_NONE,
};

/* The five effect-state handlers DuelEffect_UpdateState runs. */
DuelEffectHandler
    gDuelEffect_apfnStateHandler[DUEL_EFFECT_STATE_HANDLER_COUNT] = {
    func_80028310,
    func_80028310,
    func_800283F4,
    func_800289AC,
    func_800289B4,
};
