#ifndef MEMORIES_DECOMP_DUEL_DISPLAY_H
#define MEMORIES_DECOMP_DUEL_DISPLAY_H

#include "color_constants.h"

#define DUEL_DISPLAY_COLOR_NORMAL COLOR_RGB24_NEUTRAL_GREY
#define DUEL_DISPLAY_COLOR_DIMMED COLOR_RGB24_DIM_GREY

#define DUEL_CARD_READBACK_WIDTH_WORDS 0x8C
#define DUEL_CARD_READBACK_HEIGHT 0xC4
#define DUEL_CARD_READBACK_WORD_COUNT \
    (DUEL_CARD_READBACK_WIDTH_WORDS * DUEL_CARD_READBACK_HEIGHT)

void func_800164FC(void);

#endif
