#ifndef MEMORIES_DECOMP_DUEL_DISPLAY_H
#define MEMORIES_DECOMP_DUEL_DISPLAY_H

#include "color_constants.h"

#define DUEL_DISPLAY_COLOR_NORMAL COLOR_RGB24_NEUTRAL_GREY
#define DUEL_DISPLAY_COLOR_DIMMED COLOR_RGB24_DIM_GREY

#define DUEL_CARD_READBACK_WIDTH_WORDS 0x8C
/* 0xD4 in the European build, whose wrapper defines it. */
#ifndef DUEL_CARD_READBACK_HEIGHT
#define DUEL_CARD_READBACK_HEIGHT 0xC4
#endif
#define DUEL_CARD_READBACK_WORD_COUNT \
    (DUEL_CARD_READBACK_WIDTH_WORDS * DUEL_CARD_READBACK_HEIGHT)

void Duel_DrawFieldCards(void);

#endif
