#ifndef MEMORIES_DECOMP_FILE_CONSTANTS_H
#define MEMORIES_DECOMP_FILE_CONSTANTS_H

/* Logical sector units used by the resident loader; see notes/mrg-files.md. */
#define FILE_SECTOR_SHIFT 11
#define FILE_SECTOR_SIZE (1 << FILE_SECTOR_SHIFT)

#define FILE_TRANSFER_DEFAULT_IMAGE_WORD_WIDTH 0x40
#define FILE_TRANSFER_DEFAULT_IMAGE_HEIGHT 0x10

#define FILE_POSITION_TABLE_CAPACITY 7
#define FILE_TRANSFER_FILE_INDEX_MASK 0xF
#define FILE_TRANSFER_FLAG_SECTOR_RANGE 0x80000
#define FILE_LBA_INDEX_SD_SE 4
#define FILE_LBA_INDEX_SD_BGM 5
#define FILE_LBA_INDEX_MASTER_XA 6

#define FILE_TRANSFER_DESCRIPTOR_STATUS_FLAGS_BYTE_OFFSET 0x2C
#define FILE_TRANSFER_DESCRIPTOR_STATE_BYTE_OFFSET 0x46
#define FILE_TRANSFER_DESCRIPTOR_SUBSTATE_BYTE_OFFSET 0x47

#endif
