#ifndef MEMORIES_DECOMP_FILE_CONSTANTS_H
#define MEMORIES_DECOMP_FILE_CONSTANTS_H

/* Logical sector units used by the resident loader; see notes/mrg-files.md. */
#define FILE_SECTOR_SHIFT 11
#define FILE_SECTOR_SIZE (1 << FILE_SECTOR_SHIFT)

#define FILE_WA_DUEL_RESULTS_START_SECTOR 0x1DAB
#define FILE_WA_DUEL_RESULTS_SECTOR_COUNT 0x22
#define FILE_WA_CAMPAIGN_SCENE_START_SECTOR 0x1E57
#define FILE_WA_CAMPAIGN_SCENE_SECTOR_COUNT 0x31
#define FILE_WA_FREE_DUEL_START_SECTOR 0x1E88
#define FILE_WA_FREE_DUEL_SECTOR_COUNT 0x57
#define FILE_WA_NAME_ENTRY_START_SECTOR 0x1EDF
#define FILE_WA_NAME_ENTRY_SECTOR_COUNT 0x50
#define FILE_WA_PASSWORD_START_SECTOR 0x1F2F
#define FILE_WA_PASSWORD_SECTOR_COUNT 0x56
#define FILE_WA_MENU_ASSETS_START_SECTOR 0x1FA7
#define FILE_WA_MENU_ASSETS_SECTOR_COUNT 0x32
#define FILE_WA_EGYPT_OVERWORLD_START_SECTOR 0x1FD9
#define FILE_WA_EGYPT_OVERWORLD_SECTOR_COUNT 0x9E

#define FILE_TRANSFER_DEFAULT_IMAGE_WORD_WIDTH 0x40
#define FILE_TRANSFER_DEFAULT_IMAGE_HEIGHT 0x10

#define FILE_POSITION_TABLE_CAPACITY 7
#define FILE_TRANSFER_FILE_INDEX_MASK 0xF
#define FILE_TRANSFER_FLAG_SECTOR_RANGE 0x80000
#define FILE_LBA_INDEX_SD_SE 4
#define FILE_LBA_INDEX_SD_BGM 5
#define FILE_LBA_INDEX_MASTER_XA 6

#define FILE_TRANSFER_DESCRIPTOR_STATUS_FLAGS_BYTE_OFFSET 0x2C
#define FILE_TRANSFER_DESCRIPTOR_STATE_BYTE_OFFSET 0x46
#define FILE_TRANSFER_DESCRIPTOR_SUBSTATE_BYTE_OFFSET 0x47

#endif
