#ifndef MEMORIES_DECOMP_SAVE_DATA_H
#define MEMORIES_DECOMP_SAVE_DATA_H

#define SAVE_DATA_HEADER_SIZE 0x200
#define SAVE_DATA_STATE_SIZE 0x680
#define SAVE_DATA_REPLICATED_STATE_SIZE (SAVE_DATA_STATE_SIZE * 2)
#define SAVE_DATA_DUPLICATE_STATE_OFFSET \
    (SAVE_DATA_HEADER_SIZE + SAVE_DATA_STATE_SIZE)
#define SAVE_DATA_SEQUENCE_OFFSET 0x404
#define SAVE_DATA_VBLANK_COUNTER_OFFSET 0x408
#define SAVE_DATA_PLAYER_NAME_OFFSET 0x40C
#define SAVE_DATA_PLAYER_NAME_CHAR_COUNT 6
#define SAVE_DATA_PLAYER_NAME_SIZE \
    (SAVE_DATA_PLAYER_NAME_CHAR_COUNT * sizeof(u16))
#define SAVE_DATA_CAMPAIGN_SCENE_INDEX_OFFSET 0x5DC
#define SAVE_DATA_OUTPUT_TYPE_OFFSET 0x5DE

#define SAVE_DATA_PRIMARY_LENGTH 0x340
#define SAVE_DATA_PRIMARY_MASK_LAST_OFFSET 0x378
#define SAVE_DATA_PRIMARY_MASK_WORD_COUNT 15
#define SAVE_DATA_PRIMARY_CHECKSUM_OFFSET \
    (SAVE_DATA_PRIMARY_MASK_LAST_OFFSET + sizeof(s32))

#define SAVE_DATA_SECONDARY_OFFSET 0x380
#define SAVE_DATA_SECONDARY_LENGTH 0x6C
#define SAVE_DATA_SECONDARY_MASK_LAST_OFFSET 0x3F8
#define SAVE_DATA_SECONDARY_MASK_WORD_COUNT 4
#define SAVE_DATA_SECONDARY_CHECKSUM_OFFSET \
    (SAVE_DATA_SECONDARY_MASK_LAST_OFFSET + sizeof(s32))

#define SAVE_DATA_TERTIARY_OFFSET 0x400
#define SAVE_DATA_TERTIARY_LENGTH 0x204
#define SAVE_DATA_TERTIARY_CHECKSUM_OFFSET \
    (SAVE_DATA_TERTIARY_OFFSET + SAVE_DATA_TERTIARY_LENGTH)
#define SAVE_DATA_TERTIARY_MASK_LAST_OFFSET 0x624
#define SAVE_DATA_TERTIARY_MASK_WORD_COUNT 8
#define SAVE_DATA_RESERVED_TAIL_OFFSET \
    (SAVE_DATA_TERTIARY_MASK_LAST_OFFSET + sizeof(s32))
#define SAVE_DATA_RESERVED_TAIL_SIZE \
    (SAVE_DATA_STATE_SIZE - SAVE_DATA_RESERVED_TAIL_OFFSET)
#define SAVE_DATA_RESERVED_TAIL_PAYLOAD_OFFSET \
    (SAVE_DATA_HEADER_SIZE + SAVE_DATA_RESERVED_TAIL_OFFSET)

extern u8 gSaveData_aTransferBuffer[];
extern u8 gSaveData_aHeaderTemplate[];

u32 SaveData_NextMaskWord(void);
void SaveData_SetMaskSeed(u32);
u32 SaveData_CalcCrc16(u8 *, s32);
void SaveData_WritePrimarySecondaryIntegrity(u8 *);
void SaveData_WriteTertiaryIntegrity(u8 *);
void SaveData_BuildPayload(u8 *);
s32 SaveData_ValidateIntegrity(u8 *);

#endif
