#ifndef MEMORIES_DECOMP_SAVE_DATA_H
#define MEMORIES_DECOMP_SAVE_DATA_H

#define SAVE_DATA_HEADER_SIZE 0x200
#define SAVE_DATA_STATE_SIZE 0x680
#define SAVE_DATA_DUPLICATE_STATE_OFFSET \
    (SAVE_DATA_HEADER_SIZE + SAVE_DATA_STATE_SIZE)

#define SAVE_DATA_PRIMARY_LENGTH 0x340
#define SAVE_DATA_PRIMARY_MASK_LAST_OFFSET 0x378
#define SAVE_DATA_PRIMARY_MASK_WORD_COUNT 15
#define SAVE_DATA_PRIMARY_CHECKSUM_OFFSET \
    (SAVE_DATA_PRIMARY_MASK_LAST_OFFSET + sizeof(s32))

#define SAVE_DATA_SECONDARY_OFFSET 0x380
#define SAVE_DATA_SECONDARY_LENGTH 0x6C
#define SAVE_DATA_SECONDARY_MASK_LAST_OFFSET 0x3F8
#define SAVE_DATA_SECONDARY_MASK_WORD_COUNT 4
#define SAVE_DATA_SECONDARY_CHECKSUM_OFFSET \
    (SAVE_DATA_SECONDARY_MASK_LAST_OFFSET + sizeof(s32))

#define SAVE_DATA_TERTIARY_OFFSET 0x400
#define SAVE_DATA_TERTIARY_LENGTH 0x204
#define SAVE_DATA_TERTIARY_CHECKSUM_OFFSET \
    (SAVE_DATA_TERTIARY_OFFSET + SAVE_DATA_TERTIARY_LENGTH)
#define SAVE_DATA_TERTIARY_MASK_LAST_OFFSET 0x624
#define SAVE_DATA_TERTIARY_MASK_WORD_COUNT 8

#endif
