#ifndef YUGIOH_GAME_SOUND_VOICE_CONSTANTS_H
#define YUGIOH_GAME_SOUND_VOICE_CONSTANTS_H

#define SD_VOICE_SLOT_COUNT 4
#define SD_VOICE_SLOT_KEY_SHIFT 20
#define SD_VOICE_SLOT_FIRST_VOICE SD_VOICE_SLOT_KEY_SHIFT
#define SD_VOICE_SLOT_MASK_BASE (1 << SD_VOICE_SLOT_KEY_SHIFT)
#define SD_VOICE_SLOT_MASK_ALL \
    ((SD_VOICE_SLOT_MASK_BASE << SD_VOICE_SLOT_COUNT) - \
     SD_VOICE_SLOT_MASK_BASE)

#define SD_VOICE_LOOKUP_BYTE_OFFSET 0x44C
#define SD_VOICE_LOOKUP_CODE_MASK 0xF000
#define SD_VOICE_LOOKUP_CODE_TAG 0x4000
#define SD_VOICE_LOOKUP_BANK_COUNT 2
#define SD_VOICE_LOOKUP_BANK_ENTRY_COUNT 32
#define SD_VOICE_LOOKUP_ENTRY_COUNT \
    (SD_VOICE_LOOKUP_BANK_COUNT * SD_VOICE_LOOKUP_BANK_ENTRY_COUNT)
#define SD_VOICE_LOOKUP_INDEX_MASK (SD_VOICE_LOOKUP_BANK_ENTRY_COUNT - 1)
#define SD_VOICE_LOOKUP_BANK_FLAG 0x100
#define SD_VOICE_LOOKUP_BANK_BYTE_SHIFT 6
#define SD_VOICE_LOOKUP_BANK_BYTE_STRIDE (1 << SD_VOICE_LOOKUP_BANK_BYTE_SHIFT)
#define SD_VOICE_LOOKUP_END_BYTE_OFFSET \
    (SD_VOICE_LOOKUP_BYTE_OFFSET + \
     SD_VOICE_LOOKUP_BANK_COUNT * SD_VOICE_LOOKUP_BANK_BYTE_STRIDE)

#endif
