#ifndef YUGIOH_GAME_SOUND_VOICE_CONSTANTS_H
#define YUGIOH_GAME_SOUND_VOICE_CONSTANTS_H

#define SD_VOICE_SLOT_COUNT 4
#define SD_VOICE_SLOT_KEY_SHIFT 20
#define SD_VOICE_SLOT_FIRST_VOICE SD_VOICE_SLOT_KEY_SHIFT
#define SD_VOICE_SLOT_MASK_BASE (1 << SD_VOICE_SLOT_KEY_SHIFT)
#define SD_VOICE_SLOT_MASK_ALL \
    ((SD_VOICE_SLOT_MASK_BASE << SD_VOICE_SLOT_COUNT) - \
     SD_VOICE_SLOT_MASK_BASE)

#endif
