#ifndef YUGIOH_GAME_SOUND_SEQUENCE_CONSTANTS_H
#define YUGIOH_GAME_SOUND_SEQUENCE_CONSTANTS_H

#define SD_SEQUENCE_CHANNEL_COUNT 16
#define SD_SEQUENCE_CHANNEL_RECORD_SIZE 0x18
#define SD_SECONDARY_OBJECT_COUNT 20
#define SD_SECONDARY_OBJECT_SIZE 0x28
#define SD_SEQUENCE_TRACK_COUNT 16
#define SD_SEQUENCE_TRACK_RECORD_SIZE 0x2C

#define SD_SEQUENCE_STATUS_BIT 0x80
#define SD_SEQUENCE_STATUS_MASK 0xF0
#define SD_SEQUENCE_STATUS_SHIFT 4
#define SD_SEQUENCE_STATUS_INDEX_MASK 0x0F
#define SD_SEQUENCE_CHANNEL_MASK 0x0F

#define SD_SEQUENCE_NOTE_OFF 0x80
#define SD_SEQUENCE_NOTE_ON 0x90
#define SD_SEQUENCE_CONTROL_CHANGE 0xB0
#define SD_SEQUENCE_PROGRAM_CHANGE 0xC0
#define SD_SEQUENCE_PITCH_BEND 0xE0
#define SD_SEQUENCE_SYSEX_EVENT 0xF0
#define SD_SEQUENCE_SYSEX_END 0xF7
#define SD_SEQUENCE_META_EVENT 0xFF

#define SD_SEQUENCE_META_END_OF_TRACK 0x2F
#define SD_SEQUENCE_META_TEMPO 0x51
#define SD_SEQUENCE_META_SMPTE_OFFSET 0x54
#define SD_SEQUENCE_META_TIME_SIGNATURE 0x58
#define SD_SEQUENCE_META_KEY_SIGNATURE 0x59

#endif
