#ifndef YUGIOH_GAME_SOUND_PENDING_CONSTANTS_H
#define YUGIOH_GAME_SOUND_PENDING_CONSTANTS_H

#define SD_NOTE_RECORD_SIZE 0x08
#define SD_PENDING_ENTRY_NONE 0xFFFF
#define SD_PENDING_INPUT_IDS_BYTE_OFFSET 0x08
#define SD_PENDING_INPUT_ID_ENTRY_SIZE 2
#define SD_PENDING_INPUT_PAYLOAD_BYTE_OFFSET 0x1A0
#define SD_PENDING_INPUT_ENTRY_CAPACITY \
    ((SD_PENDING_INPUT_PAYLOAD_BYTE_OFFSET - SD_PENDING_INPUT_IDS_BYTE_OFFSET) / \
     SD_PENDING_INPUT_ID_ENTRY_SIZE)
#define SD_PENDING_INPUT_BLOCK_SHIFT 11
#define SD_PENDING_INPUT_BLOCK_SIZE (1 << SD_PENDING_INPUT_BLOCK_SHIFT)
#define SD_PENDING_INPUT_COPY_GROUP_COUNT 64

#endif
