#ifndef YUGIOH_GAME_SOUND_SEQUENCE_CONSTANTS_H
#define YUGIOH_GAME_SOUND_SEQUENCE_CONSTANTS_H

#define SD_SEQUENCE_CHANNEL_COUNT 16
#define SD_SEQUENCE_CHANNEL_RECORD_SIZE 0x18
#define SD_SECONDARY_OBJECT_COUNT 20
#define SD_SECONDARY_OBJECT_SIZE 0x28
#define SD_SECONDARY_RECORD_NONE 0x63
#define SD_SEQUENCE_TRACK_COUNT 16
#define SD_SEQUENCE_TRACK_RECORD_SIZE 0x2C
#define SD_SEQUENCE_TRACK_ARRAY_OFFSET 0x518

#define SD_SECONDARY_PAN_CENTER 0x40
#define SD_SECONDARY_PAN_LIMIT 0x80
#define SD_SECONDARY_PAN_MAX (SD_SECONDARY_PAN_LIMIT - 1)
#define SD_SECONDARY_PAN_HALF_MASK (SD_SECONDARY_PAN_CENTER - 1)
#define SD_SECONDARY_PAN_SUM_BIAS (SD_SECONDARY_PAN_CENTER * 3)

#define SD_SEQUENCE_PITCH_BEND_CENTER 0x40
#define SD_SEQUENCE_PITCH_BEND_POSITIVE_BIAS (SD_SEQUENCE_PITCH_BEND_CENTER - 1)
#define SD_SEQUENCE_PITCH_BEND_MSB_MASK 0x7F

#define SD_SEQUENCE_STATUS_BIT 0x80
#define SD_SEQUENCE_STATUS_MASK 0xF0
#define SD_SEQUENCE_STATUS_SHIFT 4
#define SD_SEQUENCE_STATUS_INDEX_MASK 0x0F
#define SD_SEQUENCE_CHANNEL_MASK 0x0F

#define SD_SEQUENCE_NOTE_OFF 0x80
#define SD_SEQUENCE_NOTE_ON 0x90
#define SD_SEQUENCE_CONTROL_CHANGE 0xB0
#define SD_SEQUENCE_PROGRAM_CHANGE 0xC0
#define SD_SEQUENCE_PITCH_BEND 0xE0
#define SD_SEQUENCE_SYSEX_EVENT 0xF0
#define SD_SEQUENCE_SYSEX_END 0xF7
#define SD_SEQUENCE_META_EVENT 0xFF

#define SD_SEQUENCE_META_END_OF_TRACK 0x2F
#define SD_SEQUENCE_META_TEMPO 0x51
#define SD_SEQUENCE_META_SMPTE_OFFSET 0x54
#define SD_SEQUENCE_META_TIME_SIGNATURE 0x58
#define SD_SEQUENCE_META_KEY_SIGNATURE 0x59

#define SD_SEQUENCE_VLQ_PAYLOAD_BITS 7
#define SD_SEQUENCE_VLQ_PAYLOAD_MASK 0x7F
#define SD_SEQUENCE_VLQ_CONTINUATION_BIT 0x80
#define SD_SEQUENCE_VLQ_INITIAL_STOP 0xFF

#define SD_SEQUENCE_CONTROL_DATA_ENTRY 6
#define SD_SEQUENCE_CONTROL_PARAMETER_SELECTOR 0x62
#define SD_SEQUENCE_CONTROL_MODE 0x63
#define SD_SEQUENCE_PARAMETER_REVERB_MODE 0x0F
#define SD_SEQUENCE_PARAMETER_REVERB_DEPTH 0x10
#define SD_SEQUENCE_LOOP_START 0x14
#define SD_SEQUENCE_LOOP_END 0x1E
#define SD_SEQUENCE_LOOP_UNCOUNTED 0x7F

#define SD_SEQUENCE_TAG_SEQ 0x53455170
#define SD_SEQUENCE_TAG_MIDI 0x6468544D
#define SD_SEQUENCE_TAG_KDT 0x2054444B
#define SD_SEQUENCE_TAG_KDT1 0x3154444B

#endif
