#ifndef TRIG_CONSTANTS_H
#define TRIG_CONSTANTS_H

#define TRIG_ANGLE_FULL_TURN 0x1000
#define TRIG_ANGLE_QUARTER_TURN (TRIG_ANGLE_FULL_TURN / 4)
#define TRIG_ANGLE_MASK (TRIG_ANGLE_FULL_TURN - 1)

#endif
