name: french_model_image_model_59284_8013a000
sha1: f7087b86d09bf7461db58f36096c576a98449d4e

options:
  basename: french_model_image_model_59284_8013a000
  base_path: ../../..
  target_path: tmp/overlays/french_model_image_model_59284_8013a000/module.bin
  elf_path: tmp/overlays/french_model_image_model_59284_8013a000/build/french_model_image_model_59284_8013a000.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/french_model_image_model_59284_8013a000/asm
  src_path: src
  build_path: tmp/overlays/french_model_image_model_59284_8013a000/build
  asset_path: tmp/overlays/french_model_image_model_59284_8013a000/assets
  cache_path: tmp/overlays/french_model_image_model_59284_8013a000/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/french_model_image_model_59284_8013a000/french_model_image_model_59284_8013a000.ld
  generated_asm_macros_directory: tmp/overlays/french_model_image_model_59284_8013a000/include
  lib_path: tmp/overlays/french_model_image_model_59284_8013a000/lib
  o_path: tmp/overlays/french_model_image_model_59284_8013a000/build
  undefined_funcs_auto_path: tmp/overlays/french_model_image_model_59284_8013a000/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/french_model_image_model_59284_8013a000/undefined_syms_auto.txt
  symbol_addrs_path:
    - config/sles_03948/overlays/model_return_two_slot0_symbols.txt
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x8013A000
    align: 4
    subsegments:
      - [0x0, data, overlays/french_model_image_model_59284_8013a000/module_header]
  - name: entry
    type: code
    start: 0x4
    vram: 0x8013A004
    align: 4
    subsegments:
      - [0x4, c, overlays/spanish_model_primary/return_two]
  - name: unclassified_tail
    type: code
    start: 0xC
    vram: 0x8013A00C
    align: 4
    subsegments:
      - [0xC, data, overlays/french_model_image_model_59284_8013a000/unclassified_tail]
  - [0x1000]
