name: french_model_variant_190_stage10_slot1
sha1: 215163c0f24b7df6fe565a39fb3c2e253b1a1ceb

options:
  basename: french_model_variant_190_stage10_slot1
  base_path: ../../..
  target_path: tmp/overlays/french_model_variant_190_stage10_slot1/module.bin
  elf_path: tmp/overlays/french_model_variant_190_stage10_slot1/build/french_model_variant_190_stage10_slot1.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/french_model_variant_190_stage10_slot1/asm
  src_path: src
  build_path: tmp/overlays/french_model_variant_190_stage10_slot1/build
  asset_path: tmp/overlays/french_model_variant_190_stage10_slot1/assets
  cache_path: tmp/overlays/french_model_variant_190_stage10_slot1/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/french_model_variant_190_stage10_slot1/french_model_variant_190_stage10_slot1.ld
  generated_asm_macros_directory: tmp/overlays/french_model_variant_190_stage10_slot1/include
  lib_path: tmp/overlays/french_model_variant_190_stage10_slot1/lib
  o_path: tmp/overlays/french_model_variant_190_stage10_slot1/build
  undefined_funcs_auto_path: tmp/overlays/french_model_variant_190_stage10_slot1/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/french_model_variant_190_stage10_slot1/undefined_syms_auto.txt
  symbol_addrs_path:
    - config/sles_03948/overlays/model_variant_190_stage10_slot1_symbols.txt
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x8017B000
    align: 4
    subsegments:
      - [0x0, data, overlays/french_model_variant_190_stage10_slot1/module_header]
  - name: entry
    type: code
    start: 0x4
    vram: 0x8017B004
    align: 4
    subsegments:
      - [0x4, c, overlays/french_model_variant/variant393_entry_slot1]
  - name: ribbon
    type: code
    start: 0xDDC
    vram: 0x8017BDDC
    align: 4
    subsegments:
      - [0xDDC, c, overlays/french_model_variant/variant393_ribbon_slot1]
  - name: helper_1704
    type: code
    start: 0x1704
    vram: 0x8017C704
    align: 4
    subsegments:
      - [0x1704, c, overlays/french_model_variant/variant393_rings_slot1]
  - name: unmatched_1B8C
    type: code
    start: 0x1B8C
    vram: 0x8017CB8C
    align: 4
    subsegments:
      - [0x1B8C, asm, overlays/french_model_variant_190_stage10_slot1/unmatched_1B8C]
  - name: unclassified_tail
    type: code
    start: 0x23B0
    vram: 0x8017D3B0
    align: 4
    subsegments:
      - [0x23B0, data, overlays/french_model_variant_190_stage10_slot1/unclassified_tail]
  - [0x5000]
