#include "../../../types.h"
#define VERSION_EUROPE
#define VERSION_EUROPE_FREE_DUEL_GET_SPARKLE_SLOT
#define VERSION_EUROPE_FREE_DUEL_UPDATE_SPARKLE
#define VERSION_EUROPE_FREE_DUEL_UPDATE_CURSOR_TWEEN
#define VERSION_EUROPE_FREE_DUEL_UPDATE_SCREEN
#define VERSION_EUROPE_FREE_DUEL_ENTRY
#include "../../free_duel/screen_runtime.c"
