name: SLPM_863.98
sha1: 4c829d5b467e8efc6e0694f4641663827c94f00f

options:
  basename: slpm_86398
  base_path: ../..
  target_path: game/japanese/SLPM_863.98
  elf_path: tmp/splat/slpm_86398/build/slpm_86398.elf
  platform: psx
  compiler: PSYQ
  endianness: little

  asm_path: tmp/splat/slpm_86398/asm
  src_path: src
  build_path: tmp/splat/slpm_86398/build
  asset_path: tmp/splat/slpm_86398/assets
  cache_path: tmp/splat/slpm_86398/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings

  ld_script_path: tmp/splat/slpm_86398/slpm_86398.ld
  generated_asm_macros_directory: tmp/splat/slpm_86398/include
  lib_path: tmp/splat/slpm_86398/lib
  o_path: tmp/splat/slpm_86398/build
  undefined_funcs_auto_path: tmp/splat/slpm_86398/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/splat/slpm_86398/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/slpm_86398/symbols.txt

  gp_value: 0x8009ae48
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2

  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subsegments:
      - [0x800, rodata, initial_data]
      - [0x30c4, asm, entry]
      - [0x3dc0, c, game/func_800136D4]
      - [0x3dd0, asm, func_800135D0]
      - [0x6e64, c, game/func_80016778]
      - [0x6e70, asm, func_80016670]
      - [0x7418, c, game/duel_draw_status_numbers]
      - [0x76f8, asm, func_80016EF8]
      - [0x7764, c, game/duel_calc_card_stats]
      - [0x77cc, asm, func_80016FCC]
      - [0x87cc, c, game/duel_card_object_helpers]
      - [0x88d8, asm, func_800180D8]
      - [0xa1a8, c, game/display_object_alpha_transition]
      - [0xa24c, asm, func_80019A4C]
      - [0xbf18, c, game/japanese/func_8001B8B8]
      - [0xbf98, asm, func_8001B798]
      - [0xd98c, c, game/display_object_property_transitions]
      - [0xdb60, asm, func_8001D360]
      - [0x14c18, c, game/japanese/duel_card_data_transfer]
      - [0x14d30, c, game/util_compare_s16]
      - [0x14d60, asm, func_80024560]
      - [0x153f4, c, game/japanese/func_80024DC8]
      - [0x15450, asm, func_80024C50]
      - [0x19b54, c, game/func_80029574]
      - [0x19b70, asm, func_80029370]
      - [0x1a490, c, game/func_80029EB0]
      - [0x1a4a4, asm, func_80029CA4]
      - [0x1ac40, c, game/func_8002A660]
      - [0x1ac98, asm, func_8002A498]
      - [0x1cb3c, c, game/duel_effect_object_pool]
      - [0x1cc94, asm, func_8002C494]
      - [0x1d160, c, game/duel_calc_guardian_star_matchup]
      - [0x1d1d4, asm, func_8002C9D4]
      - [0x1d288, c, game/campaign_test_story_flag]
      - [0x1d2c4, c, game/library_update_card_used_flag]
      - [0x1d328, asm, func_8002CB28]
      - [0x1e954, c, game/duel_effect_mark_object_if_active]
      - [0x1e998, asm, func_8002E198]
      - [0x1fed8, c, game/japanese/script_control_commands]
      - [0x1ff7c, asm, func_8002F77C]
      - [0x1ffd0, c, game/japanese/script_op_return_to_menu]
      - [0x1fffc, asm, func_8002F7FC]
      - [0x2057c, c, game/japanese/scene_script_update_slots]
      - [0x205f8, asm, func_8002FDF8]
      - [0x20638, c, game/display_object_brightness]
      - [0x20670, asm, func_8002FE70]
      - [0x230a0, c, game/func_80032B38]
      - [0x230c8, asm, func_800328C8]
      - [0x23a68, c, game/build_deck_active_card]
      - [0x23aa4, asm, func_800332A4]
      - [0x25c08, c, game/util_copy_words]
      - [0x25cb0, c, game/util_memory]
      - [0x25d50, asm, func_80035550]
      - [0x26e48, c, game/text_stream_read_u16_le]
      - [0x26e7c, c, game/text_stream_read_le]
      - [0x26ec8, asm, func_800366C8]
      - [0x270cc, c, game/japanese/widget_update_pulse_colour]
      - [0x27164, asm, func_80036964]
      - [0x27c2c, c, game/text_box_wrap_line]
      - [0x27c98, asm, func_80037498]
      - [0x2b460, c, game/japanese/text_init_decimal_digit_glyph_map]
      - [0x2b544, asm, func_8003AD44]
      - [0x2b564, c, game/japanese/input_is_pad1_confirm_pressed]
      - [0x2b574, asm, func_8003AD74]
      - [0x2ba38, c, game/japanese/text_sjis_to_glyph_codes]
      - [0x2bb0c, asm, func_8003B30C]
      - [0x312fc, c, game/japanese/display_object_stream_stop]
      - [0x31308, asm, func_80040B08]
      - [0x31314, c, game/japanese/display_object_stream_noop]
      - [0x3131c, asm, func_80040B1C]
      - [0x31b6c, c, game/japanese/display_object_stream_read_next_command]
      - [0x31c40, asm, func_80041440]
      - [0x33058, c, game/display_object_save_position]
      - [0x3306c, asm, func_8004286C]
      - [0x35370, c, game/japanese/sd_has_queued_stream_command]
      - [0x35400, asm, func_80044C00]
      - [0x363dc, c, game/japanese/func_800464F0]
      - [0x36558, asm, func_80045D58]
      - [0x394ec, c, game/func_80049600]
      - [0x3952c, asm, func_80048D2C]
      - [0x39ea0, c, game/japanese/func_80049FB4]
      - [0x39fe8, c, game/sound_spatialize_object]
      - [0x3a168, asm, func_80049968]
      - [0x3c738, c, game/func_8004C84C]
      - [0x3c7b4, asm, func_8004BFB4]
      - [0x3db94, c, game/model_word_memory]
      - [0x3dbe4, asm, func_8004D3E4]
      - [0x4c408, c, game/func_80058DD8]
      - [0x4c44c, asm, func_8005BC4C]
      - [0x4c82c, c, game/model_buffer_getters]
      - [0x4c85c, asm, func_8005C05C]
      - [0x4c8b4, c, game/func_80059284]
      - [0x4c8dc, asm, func_8005C0DC]
      - [0x4d0d8, c, game/func_80059AA8]
      - [0x4d110, asm, func_8005C910]
      - [0x4d9f8, c, game/func_8005A3D0]
      - [0x4da90, asm, func_8005D290]
      - [0x4dea0, c, game/func_8005A878]
      - [0x4deec, asm, func_8005D6EC]
      - [0x80d84, pad]

  - name: initialized_data
    type: code
    start: 0x80d90
    vram: 0x80090590
    align: 4
    subsegments:
      - [0x80d90, data, initialized_data]

  - name: bss_image
    type: bin
    start: 0x8b780
    vram: 0x8009af80
    align: 4
    subsegments:
      - [0x8b780, bin, bss_image]

  - name: reserved_zero
    type: bin
    start: 0xec798
    vram: 0x800fbf98
    align: 4
    subsegments:
      - [0xec798, bin, reserved_zero]

  - name: overlays/slot_8013a000
    type: bin
    start: 0x12a800
    vram: 0x8013a000
    align: 4
    subsegments:
      - [0x12a800, bin, overlays/slot_8013a000]

  - name: overlays/slot_80154000
    type: bin
    start: 0x144800
    vram: 0x80154000
    align: 4
    subsegments:
      - [0x144800, bin, overlays/slot_80154000]

  - name: overlays/slot_80168000
    type: bin
    start: 0x158800
    vram: 0x80168000
    align: 4
    subsegments:
      - [0x158800, bin, overlays/slot_80168000]

  - name: overlays/slot_8017a000
    type: bin
    start: 0x16a800
    vram: 0x8017a000
    align: 4
    subsegments:
      - [0x16a800, bin, overlays/slot_8017a000]

  - name: overlays/slot_80180000
    type: bin
    start: 0x170800
    vram: 0x80180000
    align: 4
    subsegments:
      - [0x170800, bin, overlays/slot_80180000]

  - name: tail_data
    type: bin
    start: 0x1ac800
    vram: 0x801bc000
    align: 4
    subsegments:
      - [0x1ac800, bin, tail_data]

  - [0x1d0800]
