name: SLPM_863.98
sha1: 4c829d5b467e8efc6e0694f4641663827c94f00f

options:
  basename: slpm_86398
  base_path: ../..
  target_path: game/japanese/SLPM_863.98
  elf_path: tmp/splat/slpm_86398/build/slpm_86398.elf
  platform: psx
  compiler: PSYQ
  endianness: little

  asm_path: tmp/splat/slpm_86398/asm
  src_path: src
  build_path: tmp/splat/slpm_86398/build
  asset_path: tmp/splat/slpm_86398/assets
  cache_path: tmp/splat/slpm_86398/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings

  ld_script_path: tmp/splat/slpm_86398/slpm_86398.ld
  generated_asm_macros_directory: tmp/splat/slpm_86398/include
  lib_path: tmp/splat/slpm_86398/lib
  o_path: tmp/splat/slpm_86398/build
  undefined_funcs_auto_path: tmp/splat/slpm_86398/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/splat/slpm_86398/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/slpm_86398/symbols.txt

  gp_value: 0x8009ae48
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2

  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

  string_encoding: ASCII
  data_string_encoding: ASCII
  rodata_string_guesser_level: 2
  data_string_guesser_level: 2

segments:
  - name: header
    type: header
    start: 0x0

  - name: main
    type: code
    start: 0x800
    vram: 0x80010000
    align: 4
    subsegments:
      - [0x800, rodata, initial_data]
      - [0x30c4, asm, entry]
      - [0x3dc0, c, game/func_800136D4]
      - [0x3dd0, asm, func_800135D0]
      - [0x5828, c, game/func_8001513C]
      - [0x589c, asm, func_8001509C]
      - [0x6e64, c, game/func_80016778]
      - [0x6e70, asm, func_80016670]
      - [0x76f8, c, game/duel_card_can_act_this_turn]
      - [0x7720, asm, func_80016F20]
      - [0x7764, c, game/duel_calc_card_stats]
      - [0x77cc, asm, func_80016FCC]
      - [0xbde0, c, game/func_8001B780]
      - [0xbe0c, asm, func_8001B60C]
      - [0xbf18, c, game/japanese/func_8001B8B8]
      - [0xbf98, asm, func_8001B798]
      - [0x11edc, c, game/duel_award_card]
      - [0x11f38, asm, func_80021738]
      - [0x14d30, c, game/util_compare_s16]
      - [0x14d60, asm, func_80024560]
      - [0x153f4, c, game/japanese/func_80024DC8]
      - [0x15450, asm, func_80024C50]
      - [0x19b54, c, game/func_80029574]
      - [0x19b70, asm, func_80029370]
      - [0x1a490, c, game/func_80029EB0]
      - [0x1a4a4, asm, func_80029CA4]
      - [0x1c080, c, game/func_8002BAA0]
      - [0x1c08c, asm, func_8002B88C]
      - [0x1caa8, c, game/duel_find_player_deck_card]
      - [0x1cae4, asm, func_8002C2E4]
      - [0x1d160, c, game/duel_calc_guardian_star_matchup]
      - [0x1d1d4, asm, func_8002C9D4]
      - [0x1d288, c, game/campaign_test_story_flag]
      - [0x1d2c4, c, game/library_update_card_used_flag]
      - [0x1d328, asm, func_8002CB28]
      - [0x1e954, c, game/duel_effect_mark_object_if_active]
      - [0x1e998, asm, func_8002E198]
      - [0x1f434, c, game/duel_is_player_deck_complete]
      - [0x1f46c, asm, func_8002EC6C]
      - [0x1ffd0, c, game/japanese/script_op_return_to_menu]
      - [0x1fffc, asm, func_8002F7FC]
      - [0x2057c, c, game/japanese/scene_script_update_slots]
      - [0x205f8, asm, func_8002FDF8]
      - [0x22584, c, game/func_8003201C]
      - [0x22624, asm, func_80031E24]
      - [0x228d8, c, game/func_80032370]
      - [0x22960, asm, func_80032160]
      - [0x230a0, c, game/func_80032B38]
      - [0x230c8, c, game/build_deck_compare_card]
      - [0x2313c, c, game/func_80032BD4]
      - [0x231b0, asm, func_800329B0]
      - [0x23a68, c, game/build_deck_active_card]
      - [0x23aa4, asm, func_800332A4]
      - [0x25b00, c, game/sorted_entry_compare]
      - [0x25b30, asm, func_80035330]
      - [0x25c08, c, game/util_copy_words]
      - [0x25cb0, c, game/util_memory]
      - [0x25d50, asm, func_80035550]
      - [0x26e48, c, game/text_stream_read_u16_le]
      - [0x26e7c, c, game/text_stream_read_le]
      - [0x26ec8, asm, func_800366C8]
      - [0x27c2c, c, game/text_box_wrap_line]
      - [0x27c98, asm, func_80037498]
      - [0x27ffc, c, game/func_800380D4]
      - [0x28038, c, game/func_80038110]
      - [0x28070, asm, func_80037870]
      - [0x28230, c, game/func_80038334]
      - [0x28284, asm, func_80037A84]
      - [0x28354, c, game/func_80038498]
      - [0x283a0, c, game/func_800384E4]
      - [0x283ec, asm, func_80037BEC]
      - [0x28880, c, game/func_800389C4]
      - [0x28894, asm, func_80038094]
      - [0x28ff8, c, game/func_80039140]
      - [0x2909c, asm, func_8003889C]
      - [0x29920, c, game/display_object_fade_mark_initialized]
      - [0x29948, asm, func_80039148]
      - [0x29d9c, c, game/func_80039F1C]
      - [0x29dc4, asm, func_800395C4]
      - [0x29e78, c, game/func_80039FF8]
      - [0x29e9c, asm, func_8003969C]
      - [0x2a018, c, game/display_effect_has_resource_entry]
      - [0x2a06c, asm, func_8003986C]
      - [0x2a7b8, c, game/func_8003A920]
      - [0x2a7f4, asm, func_80039FF4]
      - [0x2d04c, c, game/save_data_has_same_duelist_code]
      - [0x2d07c, asm, func_8003C87C]
      - [0x302f0, c, game/display_object_set_resource_variant]
      - [0x30304, c, game/display_object_update_resource_variant]
      - [0x3032c, asm, func_8003FB2C]
      - [0x30348, c, game/display_object_configure_sprite_resource]
      - [0x303ac, asm, func_8003FBAC]
      - [0x303f0, c, game/display_object_configure_screen_sprite]
      - [0x30468, asm, func_8003FC68]
      - [0x31b6c, c, game/japanese/display_object_stream_read_next_command]
      - [0x31c40, asm, func_80041440]
      - [0x328b8, c, game/display_object_reset_velocity]
      - [0x328e0, c, game/display_object_step_position_x]
      - [0x32908, c, game/display_object_step_position_y]
      - [0x32930, c, game/display_object_step_position_z]
      - [0x32958, asm, func_80042158]
      - [0x329e8, c, game/display_object_step_toward_zero]
      - [0x32a20, asm, func_80042220]
      - [0x32a78, c, game/display_object_mark_initialized]
      - [0x32aa0, asm, func_800422A0]
      - [0x33058, c, game/display_object_save_position]
      - [0x3306c, asm, func_8004286C]
      - [0x35370, c, game/japanese/sd_has_queued_stream_command]
      - [0x35400, asm, func_80044C00]
      - [0x37b3c, c, game/func_80047C50]
      - [0x37b5c, asm, func_8004735C]
      - [0x3bd58, c, game/sd_advance_sequence_position]
      - [0x3bd6c, asm, func_8004B56C]
      - [0x3db94, c, game/model_word_memory]
      - [0x3dbe4, asm, func_8004D3E4]
      - [0x3fe14, c, game/func_8005FBC4]
      - [0x3fe6c, asm, func_8004F66C]
      - [0x4c498, c, game/japanese/model_get_slot_animation_speed]
      - [0x4c4c4, asm, func_8005BCC4]
      - [0x4d0d8, c, game/func_80059AA8]
      - [0x4d110, asm, func_8005C910]
      - [0x4d9f8, c, game/func_8005A3D0]
      - [0x4da90, asm, func_8005D290]
      - [0x5b70c, c, game/triplet_set_components]
      - [0x5b71c, c, game/func_8006C30C]
      - [0x5b740, c, game/func_8006C330]
      - [0x5b78c, asm, func_8006AF8C]
      - [0x80d84, pad]

  - name: initialized_data
    type: code
    start: 0x80d90
    vram: 0x80090590
    align: 4
    subsegments:
      - [0x80d90, data, initialized_data]

  - name: bss_image
    type: bin
    start: 0x8b780
    vram: 0x8009af80
    align: 4
    subsegments:
      - [0x8b780, bin, bss_image]

  - name: reserved_zero
    type: bin
    start: 0xec798
    vram: 0x800fbf98
    align: 4
    subsegments:
      - [0xec798, bin, reserved_zero]

  - name: overlays/slot_8013a000
    type: bin
    start: 0x12a800
    vram: 0x8013a000
    align: 4
    subsegments:
      - [0x12a800, bin, overlays/slot_8013a000]

  - name: overlays/slot_80154000
    type: bin
    start: 0x144800
    vram: 0x80154000
    align: 4
    subsegments:
      - [0x144800, bin, overlays/slot_80154000]

  - name: overlays/slot_80168000
    type: bin
    start: 0x158800
    vram: 0x80168000
    align: 4
    subsegments:
      - [0x158800, bin, overlays/slot_80168000]

  - name: overlays/slot_8017a000
    type: bin
    start: 0x16a800
    vram: 0x8017a000
    align: 4
    subsegments:
      - [0x16a800, bin, overlays/slot_8017a000]

  - name: overlays/slot_80180000
    type: bin
    start: 0x170800
    vram: 0x80180000
    align: 4
    subsegments:
      - [0x170800, bin, overlays/slot_80180000]

  - name: tail_data
    type: bin
    start: 0x1ac800
    vram: 0x801bc000
    align: 4
    subsegments:
      - [0x1ac800, bin, tail_data]

  - [0x1d0800]
