#include "../../types.h"

#define VERSION_EUROPE
#define VERSION_EUROPE_DEBUG_EFFECT_SCREEN_INPUT
#define VERSION_EUROPE_DEBUG_EFFECT_CONTROLLER
#define VERSION_EUROPE_DUEL_EFFECT_PREVIEW_HUD
#define DEBUG_EFFECT_PAGE1_FIELD_32 0x0E
#define DEBUG_EFFECT_COORDINATE_OFFSET 4
#define DEBUG_EFFECT_PAGE_OFFSET 6
#define DEBUG_EFFECT_STATE_SIZE 7

#include "../debug_effect_screen.c"
