#include "../../types.h"

#define VERSION_EUROPE
#define VERSION_EUROPE_MEM_CARD_DIALOG_UPDATE_TRADE_SAVE
#define VERSION_EUROPE_MEM_CARD_DIALOG_STEP_SLIDE
#define VERSION_EUROPE_MEM_CARD_DIALOG_CREATE_OBJECT
#define MEM_CARD_DIALOG_TRADE_SAVE_INITIAL_MESSAGE 0xB7
#define DIALOG_BOX_X 0x08

#include "../mem_card_dialog_runtime.c"
