# Baseline image only: instruction-shaped bytes remain unclassified.
name: italian_model_image_model_98202_8017a000
sha1: 6cd62b58f7e8d468b43eb01e793cadcfd0bc15e2

options:
  basename: italian_model_image_model_98202_8017a000
  base_path: ../../..
  target_path: tmp/overlays/italian_model_image_model_98202_8017a000/module.bin
  elf_path: tmp/overlays/italian_model_image_model_98202_8017a000/build/italian_model_image_model_98202_8017a000.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/italian_model_image_model_98202_8017a000/asm
  src_path: src
  build_path: tmp/overlays/italian_model_image_model_98202_8017a000/build
  asset_path: tmp/overlays/italian_model_image_model_98202_8017a000/assets
  cache_path: tmp/overlays/italian_model_image_model_98202_8017a000/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/italian_model_image_model_98202_8017a000/italian_model_image_model_98202_8017a000.ld
  generated_asm_macros_directory: tmp/overlays/italian_model_image_model_98202_8017a000/include
  lib_path: tmp/overlays/italian_model_image_model_98202_8017a000/lib
  o_path: tmp/overlays/italian_model_image_model_98202_8017a000/build
  undefined_funcs_auto_path: tmp/overlays/italian_model_image_model_98202_8017a000/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/italian_model_image_model_98202_8017a000/undefined_syms_auto.txt
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: unclassified_image
    type: code
    start: 0x0
    vram: 0x8017a000
    align: 4
    subsegments:
      - [0x0, data, overlays/italian_model_image_model_98202_8017a000/unclassified_image]
  - [0x1000]
