name: german_password_b
sha1: af9d0e31313bfa294350f82b0168643158d72e17

options:
  basename: german_password_b
  base_path: ../../..
  target_path: tmp/overlays/german_password_b/module.bin
  elf_path: tmp/overlays/german_password_b/build/german_password_b.elf
  platform: psx
  compiler: PSYQ
  endianness: little

  asm_path: tmp/overlays/german_password_b/asm
  src_path: src
  build_path: tmp/overlays/german_password_b/build
  asset_path: tmp/overlays/german_password_b/assets
  cache_path: tmp/overlays/german_password_b/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings

  ld_script_path: tmp/overlays/german_password_b/german_password_b.ld
  generated_asm_macros_directory: tmp/overlays/german_password_b/include
  lib_path: tmp/overlays/german_password_b/lib
  o_path: tmp/overlays/german_password_b/build
  undefined_funcs_auto_path: tmp/overlays/german_password_b/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/german_password_b/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/sles_03949/overlays/password_symbols.txt

  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2

  section_order:
    - ".rodata"
    - ".text"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x80168000
    align: 4
    subsegments:
      - [0x0, data, overlays/german_password_b/module_header]

  - name: module
    type: code
    start: 0x4
    vram: 0x80168004
    align: 4
    subsegments:
      - [0x4, .rodata, overlays/european/password_b/shop_update_runtime]
      - [0x18, c, overlays/european/password_b/display_object_helper]
      - [0x9C, c, overlays/european/password_b/build_keyboard_text_box]
      - [0xF8, c, overlays/european/password_b/selection_frame]
      - [0x344, c, overlays/european/password_b/init]
      - [0x6DC, c, overlays/european/password_b/glyph_lookup]
      - [0x758, c, overlays/european/password_b/update_glyph_pulse]
      - [0x878, c, overlays/european/password_b/glyph_effects]
      - [0xB24, c, overlays/european/password_b/glyph_transfer_runtime]
      - [0xEDC, c, overlays/european/password_b/adjust_length]
      - [0xF7C, c, overlays/european/password_b/update_keyboard]
      - [0x1554, c, overlays/european/password_b/update_dialog]
      - [0x1A1C, c, overlays/european/password_b/poll_completion]
      - [0x1A44, c, overlays/european/password_b/refresh_displays]
      - [0x1B68, c, overlays/european/password_b/shop_cursor_runtime]
      - [0x1E64, c, overlays/european/password_b/init_shop_screen]
      - [0x20E8, c, overlays/european/password_b/shop_update_runtime]
      - [0x2714, c, overlays/european/password_b/starter_deck]
      - [0x2850, c, overlays/european/password_b/main]
      - [0x2904, data, overlays/german_password_b/data_2904]
      - [0x7060, data, overlays/german_password_b/data]

  - [0x7800]
