name: spanish_model_variant_712_stage9_slot0
sha1: 4945cfac4ea0b6d9f592d08e4dfada3d317660fb

options:
  basename: spanish_model_variant_712_stage9_slot0
  base_path: ../../..
  target_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/module.bin
  elf_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/build/spanish_model_variant_712_stage9_slot0.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/asm
  src_path: src
  build_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/build
  asset_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/assets
  cache_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/spanish_model_variant_712_stage9_slot0.ld
  generated_asm_macros_directory: tmp/overlays/spanish_model_variant_712_stage9_slot0/include
  lib_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/lib
  o_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/build
  undefined_funcs_auto_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/spanish_model_variant_712_stage9_slot0/undefined_syms_auto.txt
  symbol_addrs_path:
    - config/sles_03951/overlays/model_variant_712_stage9_slot0_symbols.txt
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x8013B000
    align: 4
    subsegments:
      - [0x0, data, overlays/spanish_model_variant_712_stage9_slot0/module_header]
  - name: unmatched_4
    type: code
    start: 0x4
    vram: 0x8013B004
    align: 4
    subsegments:
      - [0x4, asm, overlays/spanish_model_variant_712_stage9_slot0/unmatched_4]
  - name: helper_135C
    type: code
    start: 0x135C
    vram: 0x8013C35C
    align: 4
    subsegments:
      - [0x135C, c, overlays/french_model_variant/variant476_sheet]
  - name: unmatched_170C
    type: code
    start: 0x170C
    vram: 0x8013C70C
    align: 4
    subsegments:
      - [0x170C, asm, overlays/spanish_model_variant_712_stage9_slot0/unmatched_170C]
  - name: webs
    type: code
    start: 0x20BC
    vram: 0x8013D0BC
    align: 4
    subsegments:
      - [0x20BC, c, overlays/french_model_variant/variant476_webs]
  - name: helper_247C
    type: code
    start: 0x247C
    vram: 0x8013D47C
    align: 4
    subsegments:
      - [0x247C, c, overlays/french_model_variant/variant476_curtains]
  - name: helper_2848
    type: code
    start: 0x2848
    vram: 0x8013D848
    align: 4
    subsegments:
      - [0x2848, c, overlays/french_model_variant/variant476_globe]
  - name: helper_2DD4
    type: code
    start: 0x2DD4
    vram: 0x8013DDD4
    align: 4
    subsegments:
      - [0x2DD4, c, overlays/french_model_variant/variant476_screen_grid]
  - name: unclassified_tail
    type: code
    start: 0x3374
    vram: 0x8013E374
    align: 4
    subsegments:
      - [0x3374, data, overlays/spanish_model_variant_712_stage9_slot0/unclassified_tail]
  - [0x5000]
