name: spanish_model_variant_630_stage8_slot1
sha1: cf6c463244d1c148351dd9aa3922477df91a7732

options:
  basename: spanish_model_variant_630_stage8_slot1
  base_path: ../../..
  target_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/module.bin
  elf_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/build/spanish_model_variant_630_stage8_slot1.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/asm
  src_path: src
  build_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/build
  asset_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/assets
  cache_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/spanish_model_variant_630_stage8_slot1.ld
  generated_asm_macros_directory: tmp/overlays/spanish_model_variant_630_stage8_slot1/include
  lib_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/lib
  o_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/build
  undefined_funcs_auto_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/spanish_model_variant_630_stage8_slot1/undefined_syms_auto.txt
  symbol_addrs_path:
    - config/sles_03951/overlays/model_variant_630_stage8_slot1_symbols.txt
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x8017B000
    align: 4
    subsegments:
      - [0x0, data, overlays/spanish_model_variant_630_stage8_slot1/module_header]
  - name: unmatched_4
    type: code
    start: 0x4
    vram: 0x8017B004
    align: 4
    subsegments:
      - [0x4, asm, overlays/spanish_model_variant_630_stage8_slot1/unmatched_4]
  - name: unmatched_1174
    type: code
    start: 0x1174
    vram: 0x8017C174
    align: 4
    subsegments:
      - [0x1174, asm, overlays/spanish_model_variant_630_stage8_slot1/unmatched_1174]
  - name: unmatched_1560
    type: code
    start: 0x1560
    vram: 0x8017C560
    align: 4
    subsegments:
      - [0x1560, asm, overlays/spanish_model_variant_630_stage8_slot1/unmatched_1560]
  - name: unmatched_1F2C
    type: code
    start: 0x1F2C
    vram: 0x8017CF2C
    align: 4
    subsegments:
      - [0x1F2C, asm, overlays/spanish_model_variant_630_stage8_slot1/unmatched_1F2C]
  - name: unmatched_2924
    type: code
    start: 0x2924
    vram: 0x8017D924
    align: 4
    subsegments:
      - [0x2924, c, overlays/french_model_variant/variant442_webs_slot1]
  - name: unmatched_2CE8
    type: code
    start: 0x2CE8
    vram: 0x8017DCE8
    align: 4
    subsegments:
      - [0x2CE8, asm, overlays/spanish_model_variant_630_stage8_slot1/unmatched_2CE8]
  - name: helper_3334
    type: code
    start: 0x3334
    vram: 0x8017E334
    align: 4
    subsegments:
      - [0x3334, c, overlays/french_model_variant/variant442_bands_slot1]
  - name: helper_3A40
    type: code
    start: 0x3A40
    vram: 0x8017EA40
    align: 4
    subsegments:
      - [0x3A40, c, overlays/french_model_variant/variant442_spokes_slot1]
  - name: helper_3D50
    type: code
    start: 0x3D50
    vram: 0x8017ED50
    align: 4
    subsegments:
      - [0x3D50, c, overlays/french_model_variant/variant442_rings_slot1]
  - name: helper_40CC
    type: code
    start: 0x40CC
    vram: 0x8017F0CC
    align: 4
    subsegments:
      - [0x40CC, c, overlays/french_model_variant/variant442_quad_slot1]
  - name: unclassified_tail
    type: code
    start: 0x4430
    vram: 0x8017F430
    align: 4
    subsegments:
      - [0x4430, data, overlays/spanish_model_variant_630_stage8_slot1/unclassified_tail]
  - [0x5000]
