name: spanish_model_variant_116_stage8_slot1
sha1: 04a1450ca36b14b91eb01678ed52a4c69b672d3c

options:
  basename: spanish_model_variant_116_stage8_slot1
  base_path: ../../..
  target_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/module.bin
  elf_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/build/spanish_model_variant_116_stage8_slot1.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/asm
  src_path: src
  build_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/build
  asset_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/assets
  cache_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/spanish_model_variant_116_stage8_slot1.ld
  generated_asm_macros_directory: tmp/overlays/spanish_model_variant_116_stage8_slot1/include
  lib_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/lib
  o_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/build
  undefined_funcs_auto_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/spanish_model_variant_116_stage8_slot1/undefined_syms_auto.txt
  symbol_addrs_path:
    - config/sles_03951/overlays/model_variant_116_stage8_slot1_symbols.txt
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x8017B000
    align: 4
    subsegments:
      - [0x0, data, overlays/spanish_model_variant_116_stage8_slot1/module_header]
  - name: entry
    type: code
    start: 0x4
    vram: 0x8017B004
    align: 4
    subsegments:
      - [0x4, c, overlays/french_model_variant/variant475_entry_slot1]
  - name: ribbons
    type: code
    start: 0xE98
    vram: 0x8017BE98
    align: 4
    subsegments:
      - [0xE98, c, overlays/spanish_model_variant/variant475_ribbons_slot1]
  - name: sheets
    type: code
    start: 0x1978
    vram: 0x8017C978
    align: 4
    subsegments:
      - [0x1978, c, overlays/spanish_model_variant/variant475_sheets_slot1]
  - name: quads
    type: code
    start: 0x1E34
    vram: 0x8017CE34
    align: 4
    subsegments:
      - [0x1E34, c, overlays/spanish_model_variant/variant475_quads_slot1]
  - name: strand
    type: code
    start: 0x21E0
    vram: 0x8017D1E0
    align: 4
    subsegments:
      - [0x21E0, c, overlays/spanish_model_variant/variant475_strand_slot1]
  - name: streamers
    type: code
    start: 0x2520
    vram: 0x8017D520
    align: 4
    subsegments:
      - [0x2520, c, overlays/french_model_variant/variant475_streamers_slot1]
  - name: unclassified_tail
    type: code
    start: 0x2D38
    vram: 0x8017DD38
    align: 4
    subsegments:
      - [0x2D38, data, overlays/spanish_model_variant_116_stage8_slot1/unclassified_tail]
  - [0x5000]
