name: spanish_model_variant_478_stage10_slot1
sha1: a976db778f33741fadb5364b32e6307164144428

options:
  basename: spanish_model_variant_478_stage10_slot1
  base_path: ../../..
  target_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/module.bin
  elf_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/build/spanish_model_variant_478_stage10_slot1.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/asm
  src_path: src
  build_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/build
  asset_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/assets
  cache_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/spanish_model_variant_478_stage10_slot1.ld
  generated_asm_macros_directory: tmp/overlays/spanish_model_variant_478_stage10_slot1/include
  lib_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/lib
  o_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/build
  undefined_funcs_auto_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/spanish_model_variant_478_stage10_slot1/undefined_syms_auto.txt
  symbol_addrs_path:
    - config/sles_03951/overlays/model_variant_478_stage10_slot1_symbols.txt
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x8017B000
    align: 4
    subsegments:
      - [0x0, data, overlays/spanish_model_variant_478_stage10_slot1/module_header]
  - name: unmatched_4
    type: code
    start: 0x4
    vram: 0x8017B004
    align: 4
    subsegments:
      - [0x4, asm, overlays/spanish_model_variant_478_stage10_slot1/unmatched_4]
  - name: helper_1034
    type: code
    start: 0x1034
    vram: 0x8017C034
    align: 4
    subsegments:
      - [0x1034, c, overlays/spanish_model_variant/variant445_bands_slot1]
  - name: helper_17A8
    type: code
    start: 0x17A8
    vram: 0x8017C7A8
    align: 4
    subsegments:
      - [0x17A8, c, overlays/french_model_variant/variant445_sheets_slot1]
  - name: helper_1C8C
    type: code
    start: 0x1C8C
    vram: 0x8017CC8C
    align: 4
    subsegments:
      - [0x1C8C, c, overlays/french_model_variant/variant445_webs_slot1]
  - name: helper_21F0
    type: code
    start: 0x21F0
    vram: 0x8017D1F0
    align: 4
    subsegments:
      - [0x21F0, c, overlays/french_model_variant/variant445_spokes_slot1]
  - name: helper_24F8
    type: code
    start: 0x24F8
    vram: 0x8017D4F8
    align: 4
    subsegments:
      - [0x24F8, c, overlays/french_model_variant/variant445_rings_slot1]
  - name: helper_2874
    type: code
    start: 0x2874
    vram: 0x8017D874
    align: 4
    subsegments:
      - [0x2874, c, overlays/french_model_variant/variant445_quad_slot1]
  - name: unmatched_2BD8
    type: code
    start: 0x2BD8
    vram: 0x8017DBD8
    align: 4
    subsegments:
      - [0x2BD8, asm, overlays/spanish_model_variant_478_stage10_slot1/unmatched_2BD8]
  - name: unclassified_tail
    type: code
    start: 0x3594
    vram: 0x8017E594
    align: 4
    subsegments:
      - [0x3594, data, overlays/spanish_model_variant_478_stage10_slot1/unclassified_tail]
  - [0x5000]
