name: main_menu
sha1: 5a6aa8abe6768b0f6beef0d75376bdb087b87572

options:
  basename: main_menu
  base_path: ../../..
  target_path: tmp/overlays/main_menu/module.bin
  elf_path: tmp/overlays/main_menu/build/main_menu.elf
  platform: psx
  compiler: PSYQ
  endianness: little

  asm_path: tmp/overlays/main_menu/asm
  src_path: src
  build_path: tmp/overlays/main_menu/build
  asset_path: tmp/overlays/main_menu/assets
  cache_path: tmp/overlays/main_menu/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings

  ld_script_path: tmp/overlays/main_menu/main_menu.ld
  generated_asm_macros_directory: tmp/overlays/main_menu/include
  lib_path: tmp/overlays/main_menu/lib
  o_path: tmp/overlays/main_menu/build
  undefined_funcs_auto_path: tmp/overlays/main_menu/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/main_menu/undefined_syms_auto.txt

  symbol_addrs_path:
    - notes/research/Unchiga_Symbols/modules/main_menu.txt

  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2

  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x80180000
    align: 4
    subsegments:
      - [0x0, data, overlays/main_menu/module_header]

  - name: module
    type: code
    start: 0x1C
    vram: 0x8018001C
    align: 4
    subsegments:
      - [0x1C, c, overlays/main_menu/func_8018001C]
      - [0x390, asm, overlays/main_menu/text_390]
      - [0xB4C, c, overlays/main_menu/func_80180B4C]
      - [0xD2C, c, overlays/main_menu/func_80180D2C]
      - [0xDD0, c, overlays/main_menu/func_80180DD0]
      - [0xE6C, c, overlays/main_menu/func_80180E6C]
      - [0xF50, c, overlays/main_menu/func_80180F50]
      - [0xFD8, c, overlays/main_menu/func_80180FD8]
      - [0x12B4, c, overlays/main_menu/func_801812B4]
      - [0x1728, asm, overlays/main_menu/text_1728]
      - [0x1CB8, c, overlays/main_menu/func_80181CB8]
      - [0x1E30, c, overlays/main_menu/func_80181E30]
      - [0x1EEC, c, overlays/main_menu/func_80181EEC]
      - [0x1F20, c, overlays/main_menu/func_80181F20]
      - [0x1F68, c, overlays/main_menu/func_80181F68]
      - [0x21DC, asm, overlays/main_menu/text_21DC]
      - [0x338C, c, overlays/main_menu/func_8018338C]
      - [0x3514, asm, overlays/main_menu/text_3514]
      - [0x36F4, c, overlays/main_menu/func_801836F4]
      - [0x3884, c, overlays/main_menu/func_80183884]
      - [0x3A14, c, overlays/main_menu/func_80183A14]
      - [0x3B2C, c, overlays/main_menu/func_80183B2C]
      - [0x3E8C, c, overlays/main_menu/func_80183E8C]
      - [0x3FE4, c, overlays/main_menu/func_80183FE4]
      - [0x4030, c, overlays/main_menu/func_80184030]
      - [0x40F8, c, overlays/main_menu/func_801840F8]
      - [0x416C, c, overlays/main_menu/func_8018416C]
      - [0x4254, c, overlays/main_menu/func_80184254]
      - [0x4344, c, overlays/main_menu/func_80184344]
      - [0x4454, c, overlays/main_menu/func_80184454]
      - [0x44D8, c, overlays/main_menu/func_801844D8]
      - [0x4558, data, overlays/main_menu/data]

  - [0x8000]
