name: model_variant_2_stage8_slot1
sha1: 6a00b16c87b2c6b69bfbb00ac52d5c25a77d1ce3

options:
  basename: model_variant_2_stage8_slot1
  base_path: ../../..
  target_path: tmp/overlays/model_variant_2_stage8_slot1/module.bin
  elf_path: tmp/overlays/model_variant_2_stage8_slot1/build/model_variant_2_stage8_slot1.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/model_variant_2_stage8_slot1/asm
  src_path: src
  build_path: tmp/overlays/model_variant_2_stage8_slot1/build
  asset_path: tmp/overlays/model_variant_2_stage8_slot1/assets
  cache_path: tmp/overlays/model_variant_2_stage8_slot1/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/model_variant_2_stage8_slot1/model_variant_2_stage8_slot1.ld
  generated_asm_macros_directory: tmp/overlays/model_variant_2_stage8_slot1/include
  lib_path: tmp/overlays/model_variant_2_stage8_slot1/lib
  o_path: tmp/overlays/model_variant_2_stage8_slot1/build
  undefined_funcs_auto_path: tmp/overlays/model_variant_2_stage8_slot1/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/model_variant_2_stage8_slot1/undefined_syms_auto.txt
  symbol_addrs_path:
    - config/slus_01411/overlays/model_variant_2_stage8_slot1_symbols.txt
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x8017B000
    align: 4
    subsegments:
      - [0x0, data, overlays/model_variant_2_stage8_slot1/module_header]
  - name: module
    type: code
    start: 0x4
    vram: 0x8017B004
    align: 4
    subsegments:
      - [0x4, asm, overlays/model_variant_2_stage8_slot1/text_00004]
      - [0x122C, c, overlays/model_variant/variant397_bands_slot1]
      - [0x1994, c, overlays/model_variant/variant397_sheets_slot1]
      - [0x1E7C, c, overlays/model_variant/variant397_webs_slot1]
      - [0x23F0, c, overlays/model_variant/variant397_spokes_slot1]
      - [0x26FC, c, overlays/model_variant/variant397_rings_slot1]
      - [0x2A7C, c, overlays/model_variant/variant397_quad_slot1]
      - [0x2DE4, data, overlays/model_variant_2_stage8_slot1/data]
  - [0x5000]
