name: model_variant_7_pos0_slot0
sha1: 1fb651bde21b0797b662d9f231246082dfc26458

options:
  basename: model_variant_7_pos0_slot0
  base_path: ../../..
  target_path: tmp/overlays/model_variant_7_pos0_slot0/module.bin
  elf_path: tmp/overlays/model_variant_7_pos0_slot0/build/model_variant_7_pos0_slot0.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/model_variant_7_pos0_slot0/asm
  src_path: src
  build_path: tmp/overlays/model_variant_7_pos0_slot0/build
  asset_path: tmp/overlays/model_variant_7_pos0_slot0/assets
  cache_path: tmp/overlays/model_variant_7_pos0_slot0/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/model_variant_7_pos0_slot0/model_variant_7_pos0_slot0.ld
  generated_asm_macros_directory: tmp/overlays/model_variant_7_pos0_slot0/include
  lib_path: tmp/overlays/model_variant_7_pos0_slot0/lib
  o_path: tmp/overlays/model_variant_7_pos0_slot0/build
  undefined_funcs_auto_path: tmp/overlays/model_variant_7_pos0_slot0/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/model_variant_7_pos0_slot0/undefined_syms_auto.txt
  symbol_addrs_path:
    - config/slus_01411/overlays/model_variant_7_pos0_slot0_symbols.txt
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x8013B000
    align: 4
    subsegments:
      - [0x0, data, overlays/model_variant_7_pos0_slot0/module_header]
  - name: module
    type: code
    start: 0x4
    vram: 0x8013B004
    align: 4
    subsegments:
      - [0x4, asm, overlays/model_variant_7_pos0_slot0/text_00004]
      - [0xF3C, c, overlays/model_variant/variant324_webs]
      - [0x1364, c, overlays/model_variant/variant324_fan]
      - [0x17D4, c, overlays/model_variant/variant324_bands]
      - [0x22F8, c, overlays/model_variant/variant324_draw]
      - [0x26C8, c, overlays/model_variant/variant324_spokes]
      - [0x29E0, c, overlays/model_variant/variant324_rings]
      - [0x2D64, data, overlays/model_variant_7_pos0_slot0/data]
  - [0x5000]
