name: overworld_before_coup
sha1: b80b57281f683b2aade5b0e81fc3b2f22491a64f

options:
  basename: overworld_before_coup
  base_path: ../../..
  target_path: tmp/overlays/overworld_before_coup/module.bin
  elf_path: tmp/overlays/overworld_before_coup/build/overworld_before_coup.elf
  platform: psx
  compiler: PSYQ
  endianness: little

  asm_path: tmp/overlays/overworld_before_coup/asm
  src_path: src
  build_path: tmp/overlays/overworld_before_coup/build
  asset_path: tmp/overlays/overworld_before_coup/assets
  cache_path: tmp/overlays/overworld_before_coup/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings

  ld_script_path: tmp/overlays/overworld_before_coup/overworld_before_coup.ld
  generated_asm_macros_directory: tmp/overlays/overworld_before_coup/include
  lib_path: tmp/overlays/overworld_before_coup/lib
  o_path: tmp/overlays/overworld_before_coup/build
  undefined_funcs_auto_path: tmp/overlays/overworld_before_coup/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/overworld_before_coup/undefined_syms_auto.txt

  symbol_addrs_path:
    - notes/research/Unchiga_Symbols/modules/overworld.txt

  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2

  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x80168000
    align: 4
    subsegments:
      - [0x0, data, overlays/overworld_before_coup/module_header]

  - name: module
    type: code
    start: 0x4
    vram: 0x80168004
    align: 4
    subsegments:
      - [0x4, c, overlays/overworld/teardown]
      - [0x50, asm, overlays/overworld_before_coup/text]
      - [0x18C, c, overlays/overworld/location_label]
      - [0x1E8, c, overlays/overworld/camera_from_location]
      - [0x258, c, overlays/overworld/view_update]
      - [0x310, c, overlays/overworld/camera_reset]
      - [0x388, asm, overlays/overworld_before_coup/text_388]
      - [0x588, c, overlays/overworld/spawn_location_sprite]
      - [0x66C, asm, overlays/overworld_before_coup/text_66C]
      - [0x1E54, data, overlays/overworld_before_coup/data]

  - [0x3000]
