name: password
sha1: d5d166e498f89b352fe9bf0c4176858f6c8573ab

options:
  basename: password
  base_path: ../../..
  target_path: tmp/overlays/password/module.bin
  elf_path: tmp/overlays/password/build/password.elf
  platform: psx
  compiler: PSYQ
  endianness: little

  asm_path: tmp/overlays/password/asm
  src_path: src
  build_path: tmp/overlays/password/build
  asset_path: tmp/overlays/password/assets
  cache_path: tmp/overlays/password/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings

  ld_script_path: tmp/overlays/password/password.ld
  generated_asm_macros_directory: tmp/overlays/password/include
  lib_path: tmp/overlays/password/lib
  o_path: tmp/overlays/password/build
  undefined_funcs_auto_path: tmp/overlays/password/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/password/undefined_syms_auto.txt

  symbol_addrs_path:
    - notes/research/Unchiga_Symbols/modules/password.txt

  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2

  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x80168000
    align: 4
    subsegments:
      - [0x0, data, overlays/password/module_header]

  - name: module
    type: code
    start: 0xB4
    vram: 0x801680B4
    align: 4
    subsegments:
      - [0xB4, c, overlays/password/func_801680B4]
      - [0x138, c, overlays/password/func_80168138]
      - [0x1A0, asm, overlays/password/text_1A0]
      - [0x1C08, c, overlays/password/func_80169C08]
      - [0x1C30, asm, overlays/password/text_1C30]
      - [0x1D10, c, overlays/password/func_80169D10]
      - [0x1D84, c, overlays/password/func_80169D84]
      - [0x1E20, asm, overlays/password/text_1E20]
      - [0x200C, c, overlays/password/func_8016A00C]
      - [0x202C, asm, overlays/password/text_202C]
      - [0x2304, c, overlays/password/func_8016A304]
      - [0x237C, asm, overlays/password/text_237C]
      - [0x5400, data, overlays/password/data]

  - [0x7800]
