name: japanese_password
sha1: 5fc97da6cd0085dcbbaccbce8a9b69e76be6de08

options:
  basename: japanese_password
  base_path: ../../..
  target_path: tmp/overlays/japanese_password/module.bin
  elf_path: tmp/overlays/japanese_password/build/japanese_password.elf
  platform: psx
  compiler: PSYQ
  endianness: little

  asm_path: tmp/overlays/japanese_password/asm
  src_path: src
  build_path: tmp/overlays/japanese_password/build
  asset_path: tmp/overlays/japanese_password/assets
  cache_path: tmp/overlays/japanese_password/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings

  ld_script_path: tmp/overlays/japanese_password/japanese_password.ld
  generated_asm_macros_directory: tmp/overlays/japanese_password/include
  lib_path: tmp/overlays/japanese_password/lib
  o_as_suffix: true
  undefined_funcs_auto_path: tmp/overlays/japanese_password/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/japanese_password/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/slpm_86398/overlays/password_symbols.txt

  find_file_boundaries: false
  check_consecutive_segment_types: false
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2

  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x80168000
    align: 4
    subsegments:
      - [0x0, data, overlays/japanese_password/module_header]

  - name: module
    type: code
    start: 0x18
    vram: 0x80168018
    align: 4
    subsegments:
      - [0x18, c, overlays/japanese/password/acquire_sprite]
      - [0x9C, c, overlays/japanese/password/build_keyboard_text_box]
      - [0xF0, c, overlays/japanese/password/draw_selection_frame]
      - [0x33C, c, overlays/japanese/password/init]
      - [0x5B4, c, overlays/japanese/password/get_glyph_at]
      - [0x628, c, overlays/japanese/password/update_glyph_pulse]
      - [0x728, c, overlays/japanese/password/update_glyph_fragment]
      - [0x7CC, c, overlays/japanese/password/update_glyph_shatter]
      - [0x8D0, c, overlays/japanese/password/update_caret_tween]
      - [0x9D0, c, overlays/japanese/password/update_glyph_transfer]
      - [0xBF0, asm, overlays/japanese_password/text]
      - [0xDB8, c, overlays/japanese/password/adjust_length]
      - [0xE58, asm, overlays/japanese_password/text_after_adjust_length]
      - [0x1964, c, overlays/japanese/password/poll_completion]
      - [0x198C, asm, overlays/japanese_password/text_after_poll]
      - [0x1AA8, c, overlays/japanese/password/create_message_box]
      - [0x1B44, c, overlays/japanese/password/update_digit_cursor]
      - [0x1C5C, c, overlays/japanese/password/update_digit_cursor_decoration]
      - [0x1D30, c, overlays/japanese/password/set_digit_cursor_target]
      - [0x1D50, c, overlays/japanese/password/recreate_card_preview]
      - [0x1DA4, asm, overlays/japanese_password/text_after_preview]
      - [0x2650, c, overlays/japanese/password/build_starter_deck]
      - [0x278C, asm, overlays/japanese_password/name_entry_main]
      - [0x2840, data, overlays/japanese_password/data]

  - [0x7800]
