name: japanese_password
sha1: c3dc3553518eb1136298a95fbc2dd72b3ea390be

options:
  basename: japanese_password
  base_path: ../../..
  target_path: tmp/overlays/japanese_password/module.bin
  elf_path: tmp/overlays/japanese_password/build/japanese_password.elf
  platform: psx
  compiler: PSYQ
  endianness: little

  asm_path: tmp/overlays/japanese_password/asm
  src_path: src
  build_path: tmp/overlays/japanese_password/build
  asset_path: tmp/overlays/japanese_password/assets
  cache_path: tmp/overlays/japanese_password/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings

  ld_script_path: tmp/overlays/japanese_password/japanese_password.ld
  generated_asm_macros_directory: tmp/overlays/japanese_password/include
  lib_path: tmp/overlays/japanese_password/lib
  o_path: tmp/overlays/japanese_password/build
  undefined_funcs_auto_path: tmp/overlays/japanese_password/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/japanese_password/undefined_syms_auto.txt

  symbol_addrs_path:
    - config/slpm_86398/overlays/password_symbols.txt

  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2

  section_order:
    - ".text"
    - ".rodata"
    - ".data"
    - ".sdata"
    - ".sbss"
    - ".bss"

segments:
  - name: module_header
    type: code
    start: 0x0
    vram: 0x80168000
    align: 4
    subsegments:
      - [0x0, data, overlays/japanese_password/header]

  - name: module
    type: code
    start: 0x1C
    vram: 0x8016801C
    align: 4
    subsegments:
      - [0x1C, asm, overlays/japanese_password/text]
      - [0x2650, c, overlays/japanese/password/build_starter_deck]
      - [0x278C, asm, overlays/japanese_password/name_entry_main]
      - [0x2858, data, overlays/japanese_password/data]

  - [0x7000]
