#include "../../types.h"

#define GDUEL_WSELECTEDCARDID_IN_DATA

#define VERSION_EUROPE
#define VERSION_EUROPE_CARD_LIST_CREATE_SLOT_TEXT_BOX
#define CARD_LIST_SLOT_BOX_Y 0x2C
#define CARD_LIST_SLOT_BOX_HEIGHT 0xE0
#define CARD_LIST_SLOT_FOLLOWING_FLAG 0x80
#include "../card_list_text_boxes.c"
