#include "../../types.h"

#define VERSION_EUROPE
#define D_8009C02B_IN_DATA
#define D_8009B0F4_abs D_8009B0F4
#define func_800289BC func_8002895C
#define func_80028B08 func_80028AC8
#define DUEL_RESOURCE_TRANSFER_POSITION(value) \
    ((value) * 8 + CARD_COUNT - 8)
#define DUEL_RESOURCE_TRANSFER_SECTORS 8
#define DUEL_RESOURCE_DEFAULT_X 0x18
#define DUEL_RESOURCE_VARIANT_BYTE 0
#define DUEL_RESOURCE_VARIANT_17_DELTA 0x80
#define DUEL_RESOURCE_VARIANT_15_DELTA 0x40
#define DUEL_RESOURCE_PATH_Y 0xBE
#define DUEL_RESOURCE_PATH_FIELD_5E 0xC0
#define DUEL_RESOURCE_PATH_FIELD_3C 0x1C
#define DUEL_RESOURCE_PATH_FIELD_3E 9
#define DUEL_RESOURCE_SECONDARY_X 0
#define DUEL_RESOURCE_SECONDARY_Y 0x6A
#include "../duel_effect_resource_setup.c"
