#include "../../types.h"

#define VERSION_EUROPE
#define VERSION_EUROPE_OPTIONS_LOAD_PACKAGE_STAGE
#define Options_LoadPackageStage func_8003C3C4
#define OPTIONS_PACKAGE_STAGE_MODE_0_SECTORS 48
#define OPTIONS_PACKAGE_STAGE_MODE_2_X 0x280
#define OPTIONS_PACKAGE_STAGE_MODE_2_Y 0xE0
#define OPTIONS_PACKAGE_STAGE_MODE_2_SECTORS 2
#define OPTIONS_PACKAGE_STAGE_MODE_3_SECTORS 6
#define OPTIONS_PACKAGE_STAGE_MODE_3_DESTINATION D_800101D8
#define OPTIONS_PACKAGE_STAGE_MODE_3_COMMON_TAIL 1

#include "../frontend_package_stages.c"
