#include "../../types.h"

#define VERSION_EUROPE
#define VERSION_EUROPE_INPUT_RESET_PADS
#define VERSION_EUROPE_INPUT_INIT_PADS
#define VERSION_EUROPE_INPUT_READ_RAW_PADS
#define VERSION_EUROPE_INPUT_UPDATE_PADS

#define INPUT_RAW_PAD_BUFFER_SIZE 0x24
#define INPUT_REPEAT_THRESHOLD 0x14
#define INPUT_REPEAT_RELOAD_VALUE 0x11

#include "../input_pads.c"
