#include "../../types.h"

#define VERSION_EUROPE
#define VERSION_EUROPE_FUNC_80056D7C
#define VERSION_EUROPE_MODEL_TEXTURE_TRANSFER_TAIL
#define VERSION_EUROPE_FUNC_800577B0
#define D_8009B0F4_abs D_8009B0F4
#define MODEL_TEXTURE_STAGE3_RECT_X(index) 0x280
#define MODEL_TEXTURE_STAGE3_RECT_Y(index) (((index) << 4) + 0xD8)
#define MODEL_TEXTURE_PALETTE_RECT_X 0x280
#define MODEL_TEXTURE_TAIL_ROW_Y 0xE0
#include "../model_texture_transfer.c"
