#include "../../../types.h"
#define VERSION_EUROPE
#define VERSION_EUROPE_PASSWORD_CREATE_MESSAGE_BOX
#define VERSION_EUROPE_PASSWORD_UPDATE_DIGIT_CURSOR
#define VERSION_EUROPE_PASSWORD_UPDATE_DIGIT_CURSOR_DECORATION
#define VERSION_EUROPE_PASSWORD_SET_DIGIT_CURSOR_TARGET
#define VERSION_EUROPE_PASSWORD_RECREATE_CARD_PREVIEW
#include "../../password/shop.c"
