name: european_model_image_model_48224_8013b000
sha1: e1deea0ea725081dd482940e5b9182baa82f8b65
options:
  basename: european_model_image_model_48224_8013b000
  base_path: ../../..
  target_path: tmp/overlays/european_model_image_model_48224_8013b000/module.bin
  elf_path: tmp/overlays/european_model_image_model_48224_8013b000/build/european_model_image_model_48224_8013b000.elf
  platform: psx
  compiler: PSYQ
  endianness: little
  asm_path: tmp/overlays/european_model_image_model_48224_8013b000/asm
  src_path: src
  build_path: tmp/overlays/european_model_image_model_48224_8013b000/build
  asset_path: tmp/overlays/european_model_image_model_48224_8013b000/assets
  cache_path: tmp/overlays/european_model_image_model_48224_8013b000/cache
  data_path: data
  nonmatchings_path: nonmatchings
  matchings_path: matchings
  ld_script_path: tmp/overlays/european_model_image_model_48224_8013b000/european_model_image_model_48224_8013b000.ld
  generated_asm_macros_directory: tmp/overlays/european_model_image_model_48224_8013b000/include
  lib_path: tmp/overlays/european_model_image_model_48224_8013b000/lib
  o_path: tmp/overlays/european_model_image_model_48224_8013b000/build
  undefined_funcs_auto_path: tmp/overlays/european_model_image_model_48224_8013b000/undefined_funcs_auto.txt
  undefined_syms_auto_path: tmp/overlays/european_model_image_model_48224_8013b000/undefined_syms_auto.txt
  symbol_addrs_path: [config/sles_03947/overlays/model_image_model_48224_8013b000_symbols.txt]
  find_file_boundaries: false
  check_consecutive_segment_types: false
  o_as_suffix: true
  use_legacy_include_asm: false
  create_asm_dependencies: true
  ld_dependencies: true
  subalign: 2
  section_order: [.text, .rodata, .data, .sdata, .sbss, .bss]
segments:
- name: module_header
  type: code
  start: 0
  vram: 2148773888
  align: 4
  subsegments:
  - [0, data, overlays/european_model_image_model_48224_8013b000/module_header]
- name: unmatched_4
  type: code
  start: 4
  vram: 2148773892
  align: 4
  subsegments:
  - [4, asm, overlays/european_model_image_model_48224_8013b000/unmatched_4]
- name: ribbons
  type: code
  start: 3544
  vram: 2148777432
  align: 4
  subsegments:
  - [3544, c, overlays/french_model_variant/variant450_ribbons]
- name: bands
  type: code
  start: 6036
  vram: 2148779924
  align: 4
  subsegments:
  - [6036, c, overlays/french_model_variant/variant450_bands]
- name: unmatched_1ecc
  type: code
  start: 7884
  vram: 2148781772
  align: 4
  subsegments:
  - [7884, asm, overlays/european_model_image_model_48224_8013b000/unmatched_1ecc]
- name: quads
  type: code
  start: 10176
  vram: 2148784064
  align: 4
  subsegments:
  - [10176, c, overlays/spanish_model_variant/variant450_quads]
- name: lines
  type: code
  start: 11656
  vram: 2148785544
  align: 4
  subsegments:
  - [11656, c, overlays/spanish_model_variant/variant450_lines]
- name: unmatched_310c
  type: code
  start: 12556
  vram: 2148786444
  align: 4
  subsegments:
  - [12556, asm, overlays/european_model_image_model_48224_8013b000/unmatched_310c]
- name: unclassified_tail
  type: code
  start: 14656
  vram: 2148788544
  align: 4
  subsegments:
  - [14656, data, overlays/european_model_image_model_48224_8013b000/unclassified_tail]
- [20480]
